window.CASE_LIBRARY = [
  {
    "id": "人像与摄影案例",
    "title": "人像与摄影案例",
    "cases": [
      {
        "id": "人像与摄影案例-1",
        "caseNumber": 1,
        "title": "便利店霓虹人像",
        "sourceUrl": "https://x.com/BubbleBrain/status/2045167461147042202",
        "authorHandle": "@BubbleBrain",
        "authorUrl": "https://x.com/BubbleBrain",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/portrait_case1/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/portrait_case1/output.jpg",
        "prompt": "35mm film photography with harsh convenience store fluorescent lighting mixed with colorful neon signs from outside, authentic film grain, high contrast, slight color cast, cinematic street editorial style, intimate medium shot, early 20s sexy Chinese female idol with ultra-realistic delicate refined Chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp V-shaped jawline, flawless porcelain skin with cool ivory undertone and visible specular highlights from fluorescent light, subtle skin texture and micro pores, natural dewy makeup with soft flush on cheeks, glossy natural pink lips slightly parted, subtle natural freckles across nose and cheeks, long dark brown hair in a messy high ponytail with many loose strands falling around face and neck, wearing an oversized white button-up shirt as the only top, unbuttoned at the top with deep cleavage and loosely tied at the waist, paired with a tiny black pleated mini skirt, barefoot in simple white slides, seductive casual leaning pose against the glass door of a 24-hour convenience store at late night, body slightly arched, one leg bent with foot resting against the door frame, the other leg straight, one hand holding a bottle of iced drink, the other hand lightly pulling the hem of her mini skirt, intensely seductive playful yet slightly vulnerable gaze straight at the viewer with soft doe eyes full of quiet temptation and teasing smile, bright cold fluorescent store light from inside mixed with pink and blue neon glow from outside signs, realistic reflections on glass door, blurred convenience store interior with shelves and snacks in background, authentic 35mm film color grading with harsh lighting and neon accents, extremely sharp yet soft skin rendering, natural hair strands, realistic fabric wrinkles and drape on the oversized shirt and mini skirt, no plastic skin, no digital over-sharpening, no airbrushing, no blemishes, no moles, no oily skin, no watermark, no text, authentic late-night convenience store atmosphere",
        "promptExcerpt": "35mm film photography with harsh convenience store fluorescent lighting mixed with colorful neon signs from outside, authentic film grain, high contra...",
        "category": "人像与摄影案例",
        "searchIndex": "便利店霓虹人像 人像与摄影案例 @bubblebrain 35mm film photography with harsh convenience store fluorescent lighting mixed with colorful neon signs from outside, authentic film grain, high contrast, slight color cast, cinematic street editorial style, intimate medium shot, early 20s sexy chinese female idol with ultra-realistic delicate refined chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp v-shaped jawline, flawless porcelain skin with cool ivory undertone and visible specular highlights from fluorescent light, subtle skin texture and micro pores, natural dewy makeup with soft flush on cheeks, glossy natural pink lips slightly parted, subtle natural freckles across nose and cheeks, long dark brown hair in a messy high ponytail with many loose strands falling around face and neck, wearing an oversized white button-up shirt as the only top, unbuttoned at the top with deep cleavage and loosely tied at the waist, paired with a tiny black pleated mini skirt, barefoot in simple white slides, seductive casual leaning pose against the glass door of a 24-hour convenience store at late night, body slightly arched, one leg bent with foot resting against the door frame, the other leg straight, one hand holding a bottle of iced drink, the other hand lightly pulling the hem of her mini skirt, intensely seductive playful yet slightly vulnerable gaze straight at the viewer with soft doe eyes full of quiet temptation and teasing smile, bright cold fluorescent store light from inside mixed with pink and blue neon glow from outside signs, realistic reflections on glass door, blurred convenience store interior with shelves and snacks in background, authentic 35mm film color grading with harsh lighting and neon accents, extremely sharp yet soft skin rendering, natural hair strands, realistic fabric wrinkles and drape on the oversized shirt and mini skirt, no plastic skin, no digital over-sharpening, no airbrushing, no blemishes, no moles, no oily skin, no watermark, no text, authentic late-night convenience store atmosphere https://x.com/bubblebrain/status/2045167461147042202"
      },
      {
        "id": "人像与摄影案例-2",
        "caseNumber": 2,
        "title": "电影感极简人像",
        "sourceUrl": "https://x.com/iam_miharbi/status/2045151354679665101",
        "authorHandle": "@iam_miharbi",
        "authorUrl": "https://x.com/iam_miharbi",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/portrait_case2/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/portrait_case2/output.jpg",
        "prompt": "Generate a cinematic minimal portrait of a solitary man standing in an intense orange to red gradient environment, strong silhouette lighting, deep shadow contrast, reflective glossy floor, symmetrical composition, minimal",
        "promptExcerpt": "Generate a cinematic minimal portrait of a solitary man standing in an intense orange to red gradient environment, strong silhouette lighting, deep sh...",
        "category": "人像与摄影案例",
        "searchIndex": "电影感极简人像 人像与摄影案例 @iam_miharbi generate a cinematic minimal portrait of a solitary man standing in an intense orange to red gradient environment, strong silhouette lighting, deep shadow contrast, reflective glossy floor, symmetrical composition, minimal https://x.com/iam_miharbi/status/2045151354679665101"
      },
      {
        "id": "人像与摄影案例-3",
        "caseNumber": 3,
        "title": "日式温泉旅馆人像",
        "sourceUrl": "https://x.com/BubbleBrain/status/2045092449803284923",
        "authorHandle": "@BubbleBrain",
        "authorUrl": "https://x.com/BubbleBrain",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/portrait_case3/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/portrait_case3/output.jpg",
        "prompt": "35mm film photography, warm vintage Japanese onsen ryokan aesthetic, soft ambient wooden lantern lighting mixed with gentle natural window light, subtle film grain, gentle color shift, high atmosphere editorial style, intimate medium shot, early 20s beautiful Chinese female idol with ultra-realistic delicate refined Chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp V-shaped jawline, flawless porcelain skin with warm ivory undertone, visible subtle skin texture and micro pores, soft natural makeup with dewy glow, subtle rosy flush on cheeks, natural soft pink lips slightly parted, long dark brown hair tied in a loose low bun with some messy strands falling around face and neck, wearing a loose white yukata (traditional Japanese bathrobe) deliberately slipped off one shoulder and loosely tied at the waist, the fabric slightly open revealing smooth skin and subtle cleavage, barefoot, seductive relaxed sitting pose on the edge of a traditional wooden engawa veranda at a vintage onsen ryokan, body slightly turned toward the camera, one leg bent with foot resting on the wooden floor, the other leg gently dangling, one hand lightly holding the yukata collar, the other hand resting on the wooden floor behind her for support, softly arched back to gently accentuate curves, intensely seductive yet gentle and inviting gaze straight at the viewer with soft doe eyes full of quiet temptation and warmth, warm wooden interior with paper sliding doors and distant steaming hot spring in soft focus, gentle rim lighting highlighting skin and fabric texture, authentic vintage film color grading with warm tones, extremely sharp yet soft skin rendering, natural hair strands, realistic fabric wrinkles and drape on the yukata, no plastic skin, no digital over-sharpening, no airbrushing, no blemishes, no moles, no oily skin, no watermark, no text, authentic 35mm film Japanese onsen ryokan atmosphere",
        "promptExcerpt": "35mm film photography, warm vintage Japanese onsen ryokan aesthetic, soft ambient wooden lantern lighting mixed with gentle natural window light, subt...",
        "category": "人像与摄影案例",
        "searchIndex": "日式温泉旅馆人像 人像与摄影案例 @bubblebrain 35mm film photography, warm vintage japanese onsen ryokan aesthetic, soft ambient wooden lantern lighting mixed with gentle natural window light, subtle film grain, gentle color shift, high atmosphere editorial style, intimate medium shot, early 20s beautiful chinese female idol with ultra-realistic delicate refined chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp v-shaped jawline, flawless porcelain skin with warm ivory undertone, visible subtle skin texture and micro pores, soft natural makeup with dewy glow, subtle rosy flush on cheeks, natural soft pink lips slightly parted, long dark brown hair tied in a loose low bun with some messy strands falling around face and neck, wearing a loose white yukata (traditional japanese bathrobe) deliberately slipped off one shoulder and loosely tied at the waist, the fabric slightly open revealing smooth skin and subtle cleavage, barefoot, seductive relaxed sitting pose on the edge of a traditional wooden engawa veranda at a vintage onsen ryokan, body slightly turned toward the camera, one leg bent with foot resting on the wooden floor, the other leg gently dangling, one hand lightly holding the yukata collar, the other hand resting on the wooden floor behind her for support, softly arched back to gently accentuate curves, intensely seductive yet gentle and inviting gaze straight at the viewer with soft doe eyes full of quiet temptation and warmth, warm wooden interior with paper sliding doors and distant steaming hot spring in soft focus, gentle rim lighting highlighting skin and fabric texture, authentic vintage film color grading with warm tones, extremely sharp yet soft skin rendering, natural hair strands, realistic fabric wrinkles and drape on the yukata, no plastic skin, no digital over-sharpening, no airbrushing, no blemishes, no moles, no oily skin, no watermark, no text, authentic 35mm film japanese onsen ryokan atmosphere https://x.com/bubblebrain/status/2045092449803284923"
      },
      {
        "id": "人像与摄影案例-4",
        "caseNumber": 4,
        "title": "35mm 闪光灯时尚人像",
        "sourceUrl": "https://x.com/BubbleBrain/status/2045052982728016131",
        "authorHandle": "@BubbleBrain",
        "authorUrl": "https://x.com/BubbleBrain",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/portrait_case4/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/portrait_case4/output.jpg",
        "prompt": "35mm color film photography with harsh direct on-camera flash, specular highlights on skin and clothing, strong catchlights in eyes, high contrast flash illumination, authentic film grain and color shift, high fashion fresh innocent basketball court editorial style, intimate first-person low-angle POV shot from below, early 20s sexy Chinese female idol with ultra-realistic delicate refined Chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp V-shaped jawline, flawless realistic porcelain skin with cool ivory undertone and visible flash specular highlights, fine delicate skin texture with subtle pores micro details and natural dewy glow under flash, fresh natural sporty makeup with soft dewy glow, subtle natural flush on cheeks, natural pink lips slightly parted, subtle natural freckles across nose and cheeks, long dark brown hair tied in a high playful ponytail with some loose strands framing the face and realistic loose strands, wearing a loose white tank top and white high-waisted basketball shorts, white knee-high sports socks, seductive natural leaning pose against the basketball hoop pole on the outdoor court at dusk, body angled sideways with naturally arched back and hips gently pushed back to accentuate perky round hips and sexy butt curve, one leg naturally extended forward toward the camera and the other leg slightly bent to emphasize long sexy legs, both hands lightly resting on the basketball pole at shoulder height, intensely seductive playful yet pitiable doe-eyed gaze straight at the viewer with soft vulnerable longing eyes and a gentle teasing smile full of quiet temptation and desire, harsh direct on-camera flash creating sharp specular highlights and strong catchlights, background with blurred basketball court and hoop under dusk sky, high contrast film color grading with natural flash look, extremely sharp yet soft skin rendering with authentic 35mm direct flash aesthetic, natural hair strands, realistic fabric texture on tank top and shorts with socks detail, no plastic skin, no digital over-sharpening, no airbrushing, no blemishes, no moles, no oily skin, no watermark, no text, authentic 35mm direct flash film basketball court look --ar 9:16",
        "promptExcerpt": "35mm color film photography with harsh direct on-camera flash, specular highlights on skin and clothing, strong catchlights in eyes, high contrast fla...",
        "category": "人像与摄影案例",
        "searchIndex": "35mm 闪光灯时尚人像 人像与摄影案例 @bubblebrain 35mm color film photography with harsh direct on-camera flash, specular highlights on skin and clothing, strong catchlights in eyes, high contrast flash illumination, authentic film grain and color shift, high fashion fresh innocent basketball court editorial style, intimate first-person low-angle pov shot from below, early 20s sexy chinese female idol with ultra-realistic delicate refined chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp v-shaped jawline, flawless realistic porcelain skin with cool ivory undertone and visible flash specular highlights, fine delicate skin texture with subtle pores micro details and natural dewy glow under flash, fresh natural sporty makeup with soft dewy glow, subtle natural flush on cheeks, natural pink lips slightly parted, subtle natural freckles across nose and cheeks, long dark brown hair tied in a high playful ponytail with some loose strands framing the face and realistic loose strands, wearing a loose white tank top and white high-waisted basketball shorts, white knee-high sports socks, seductive natural leaning pose against the basketball hoop pole on the outdoor court at dusk, body angled sideways with naturally arched back and hips gently pushed back to accentuate perky round hips and sexy butt curve, one leg naturally extended forward toward the camera and the other leg slightly bent to emphasize long sexy legs, both hands lightly resting on the basketball pole at shoulder height, intensely seductive playful yet pitiable doe-eyed gaze straight at the viewer with soft vulnerable longing eyes and a gentle teasing smile full of quiet temptation and desire, harsh direct on-camera flash creating sharp specular highlights and strong catchlights, background with blurred basketball court and hoop under dusk sky, high contrast film color grading with natural flash look, extremely sharp yet soft skin rendering with authentic 35mm direct flash aesthetic, natural hair strands, realistic fabric texture on tank top and shorts with socks detail, no plastic skin, no digital over-sharpening, no airbrushing, no blemishes, no moles, no oily skin, no watermark, no text, authentic 35mm direct flash film basketball court look --ar 9:16 https://x.com/bubblebrain/status/2045052982728016131"
      },
      {
        "id": "人像与摄影案例-5",
        "caseNumber": 5,
        "title": "卧室镜自拍人像",
        "sourceUrl": "https://x.com/Shinning1010/status/2045002808903020962",
        "authorHandle": "@Shinning1010",
        "authorUrl": "https://x.com/Shinning1010",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/portrait_case5/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/portrait_case5/output.jpg",
        "prompt": "A stunning 18-year-old Chinese girl with a youthful, pure face and realistic skin texture, sitting on a cozy, slightly messy bed in her bedroom. She is taking a mirror selfie with a smartphone, capturing a natural and intimate moment. Wearing casual gray loungewear and neat white crew socks. Soft natural light (golden hour) streams in from a side window, creating a warm, moody, and cinematic atmosphere. 35mm lens, sharp focus on the subject in the mirror, depth of field with a beautifully blurred background (bokeh). Photorealistic, 8K, high resolution, studio quality, masterpiece.\nNegative Prompts: no extra limbs, no deformed hands, no blur, no noise, no watermark, no text, no cartoon/anime style. Aspect Ratio: 3:4.",
        "promptExcerpt": "A stunning 18-year-old Chinese girl with a youthful, pure face and realistic skin texture, sitting on a cozy, slightly messy bed in her bedroom. She i...",
        "category": "人像与摄影案例",
        "searchIndex": "卧室镜自拍人像 人像与摄影案例 @shinning1010 a stunning 18-year-old chinese girl with a youthful, pure face and realistic skin texture, sitting on a cozy, slightly messy bed in her bedroom. she is taking a mirror selfie with a smartphone, capturing a natural and intimate moment. wearing casual gray loungewear and neat white crew socks. soft natural light (golden hour) streams in from a side window, creating a warm, moody, and cinematic atmosphere. 35mm lens, sharp focus on the subject in the mirror, depth of field with a beautifully blurred background (bokeh). photorealistic, 8k, high resolution, studio quality, masterpiece.\nnegative prompts: no extra limbs, no deformed hands, no blur, no noise, no watermark, no text, no cartoon/anime style. aspect ratio: 3:4. https://x.com/shinning1010/status/2045002808903020962"
      },
      {
        "id": "人像与摄影案例-6",
        "caseNumber": 6,
        "title": "低角度 POV 时尚大片",
        "sourceUrl": "https://x.com/BubbleBrain/status/2044705257004093537",
        "authorHandle": "@BubbleBrain",
        "authorUrl": "https://x.com/BubbleBrain",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/portrait_case6/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/portrait_case6/output.jpg",
        "prompt": "Analog 35mm film photography, high-fashion editorial portrait with intense on-camera direct flash (CCD hard flash style), intimate low-angle POV shot from slightly below (仰拍, around +15° upward angle), emphasizing long legs and elegant hourglass body proportions, 4:3 vertical format, 3/4 body shot, early 20s Korean idol-type young woman with delicate refined features, slightly upturned almond-shaped fox eyes, small sharp jawline, flawless porcelain skin with cool ivory undertone and visible specular highlights from direct flash, soft coral blush, natural dusty rose lips slightly parted, long naturally wavy dark brown hair with loose strands framing the face, wearing a slightly tilted black police peaked cap with silver badge.\nShe wears a fitted, stylish policewoman-inspired outfit: black short-sleeved collared crop top with shiny silver buttons and epaulets, a shiny silver police badge pinned on the chest, a thin black necktie loosely hanging at the front, a wide black duty belt with a silver buckle and handcuffs at the side, and a short black pleated mini skirt. Black thigh-high stockings and white low-top canvas sneakers with loose lacing add a casual contrast.\nPose: a subtle S-curve stance with weight shifted to one leg, hips angled slightly toward the camera to enhance silhouette and leg length. One hand lightly touches the cap brim or rests near the waist, while the other hand is placed at the hip or near the belt. Head tilted slightly down with a confident, self-assured upward gaze through lashes directed at the viewer, expression poised, cool, and subtly playful rather than overtly seductive.\nHarsh on-camera direct flash from front/slightly above creates strong catchlights, sharp shadows behind the subject, crisp highlights on skin, hair, badge, belt buckle, and fabric textures. Cold flash quality mixed with warm ambient window light, visible flash fall-off, Kodak Portra 400 film simulation pushed for strong analog character, warm peachy skin tones with flash highlights, subtle cyan shadows, prominent heavy analog film grain (strength 0.65, larger grain size), noticeable film halation around bright areas, strong natural vignette, slight underexposure for a raw intimate mood.\nUltra-realistic photorealistic film photography, edgy magazine editorial aesthetic, visible fabric texture and reflective metal details, delicate hair strands glowing from flash, natural skin texture with heavy film grain throughout, no plastic skin, no digital sharpness, no airbrushing, no watermark, no text, authentic 35mm film look with strong grain and flash artifacts, analog color grading.",
        "promptExcerpt": "Analog 35mm film photography, high-fashion editorial portrait with intense on-camera direct flash (CCD hard flash style), intimate low-angle POV shot...",
        "category": "人像与摄影案例",
        "searchIndex": "低角度 pov 时尚大片 人像与摄影案例 @bubblebrain analog 35mm film photography, high-fashion editorial portrait with intense on-camera direct flash (ccd hard flash style), intimate low-angle pov shot from slightly below (仰拍, around +15° upward angle), emphasizing long legs and elegant hourglass body proportions, 4:3 vertical format, 3/4 body shot, early 20s korean idol-type young woman with delicate refined features, slightly upturned almond-shaped fox eyes, small sharp jawline, flawless porcelain skin with cool ivory undertone and visible specular highlights from direct flash, soft coral blush, natural dusty rose lips slightly parted, long naturally wavy dark brown hair with loose strands framing the face, wearing a slightly tilted black police peaked cap with silver badge.\nshe wears a fitted, stylish policewoman-inspired outfit: black short-sleeved collared crop top with shiny silver buttons and epaulets, a shiny silver police badge pinned on the chest, a thin black necktie loosely hanging at the front, a wide black duty belt with a silver buckle and handcuffs at the side, and a short black pleated mini skirt. black thigh-high stockings and white low-top canvas sneakers with loose lacing add a casual contrast.\npose: a subtle s-curve stance with weight shifted to one leg, hips angled slightly toward the camera to enhance silhouette and leg length. one hand lightly touches the cap brim or rests near the waist, while the other hand is placed at the hip or near the belt. head tilted slightly down with a confident, self-assured upward gaze through lashes directed at the viewer, expression poised, cool, and subtly playful rather than overtly seductive.\nharsh on-camera direct flash from front/slightly above creates strong catchlights, sharp shadows behind the subject, crisp highlights on skin, hair, badge, belt buckle, and fabric textures. cold flash quality mixed with warm ambient window light, visible flash fall-off, kodak portra 400 film simulation pushed for strong analog character, warm peachy skin tones with flash highlights, subtle cyan shadows, prominent heavy analog film grain (strength 0.65, larger grain size), noticeable film halation around bright areas, strong natural vignette, slight underexposure for a raw intimate mood.\nultra-realistic photorealistic film photography, edgy magazine editorial aesthetic, visible fabric texture and reflective metal details, delicate hair strands glowing from flash, natural skin texture with heavy film grain throughout, no plastic skin, no digital sharpness, no airbrushing, no watermark, no text, authentic 35mm film look with strong grain and flash artifacts, analog color grading. https://x.com/bubblebrain/status/2044705257004093537"
      },
      {
        "id": "人像与摄影案例-7",
        "caseNumber": 7,
        "title": "奢华魅力美妆人像",
        "sourceUrl": "https://x.com/patrickassale/status/2044581766309060765",
        "authorHandle": "@patrickassale",
        "authorUrl": "https://x.com/patrickassale",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/portrait_case7/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/portrait_case7/output.jpg",
        "prompt": "Luxury Glam Beauty Portrait:, Beautiful Black woman, youthful spirit, creamy vanilla, silk press, mahogany red, subtle confidence, textured fabric, sapphire blue, minimal jewelry, beachside breeze, lens flare effect, nostalgic, cinematic lens, symmetrical composition, soft focus, high fashion photography, monochromatic, dewy finish, mysterious tension, layered elements\n\n*Found on Midjourney's Explore page.",
        "promptExcerpt": "Luxury Glam Beauty Portrait:, Beautiful Black woman, youthful spirit, creamy vanilla, silk press, mahogany red, subtle confidence, textured fabric, sa...",
        "category": "人像与摄影案例",
        "searchIndex": "奢华魅力美妆人像 人像与摄影案例 @patrickassale luxury glam beauty portrait:, beautiful black woman, youthful spirit, creamy vanilla, silk press, mahogany red, subtle confidence, textured fabric, sapphire blue, minimal jewelry, beachside breeze, lens flare effect, nostalgic, cinematic lens, symmetrical composition, soft focus, high fashion photography, monochromatic, dewy finish, mysterious tension, layered elements\n\n*found on midjourney's explore page. https://x.com/patrickassale/status/2044581766309060765"
      },
      {
        "id": "人像与摄影案例-8",
        "caseNumber": 8,
        "title": "9:16 Cosplayer 人像截图",
        "sourceUrl": "https://x.com/Zoulinshen/status/2045082518089810073",
        "authorHandle": "@Zoulinshen",
        "authorUrl": "https://x.com/Zoulinshen",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/portrait_case8/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/portrait_case8/output.jpg",
        "prompt": "生成一张竖版手机截图风格的图片，整体比例接近 9:16。画面中心偏上是一位真人 coser，扮演（角色名称）的二次元角色。人物为写实风格，但五官略带动漫感，皮肤细腻，眼睛稍大，表情温柔地看向镜头，坐在室内的休闲场景中，例如咖啡厅或酒吧吧台前，背景有符合场景的道具。画面最上方加入手机系统状态栏 UI，包括时间、电量、信号、网络等图标，让整张图看起来像手机截图。画面底部叠加一块宽大的半透明 galgame 风格对话框，对话框左侧放一个与画面人物对应的动漫或 Q 版头像；对话框右侧排版文字：第一行用较大字体显示与前面相同的角色名字，下面一到两行显示一段适合这个角色人设的、温柔治愈风格的简体中文台词，由你自动创作。再在对话框下方加一条操作栏，仿照 galgame UI。整体风格高清、细节丰富、光线柔和、二次元与真人写真自然融合。",
        "promptExcerpt": "生成一张竖版手机截图风格的图片，整体比例接近 9:16。画面中心偏上是一位真人 coser，扮演（角色名称）的二次元角色。人物为写实风格，但五官略带动漫感，皮肤细腻，眼睛稍大，表情温柔地看向镜头，坐在室内的休闲场景中，例如咖啡厅或酒吧吧台前，背景有符合场景的道具。画面最上方加入手机系统状态栏 UI，...",
        "category": "人像与摄影案例",
        "searchIndex": "9:16 cosplayer 人像截图 人像与摄影案例 @zoulinshen 生成一张竖版手机截图风格的图片，整体比例接近 9:16。画面中心偏上是一位真人 coser，扮演（角色名称）的二次元角色。人物为写实风格，但五官略带动漫感，皮肤细腻，眼睛稍大，表情温柔地看向镜头，坐在室内的休闲场景中，例如咖啡厅或酒吧吧台前，背景有符合场景的道具。画面最上方加入手机系统状态栏 ui，包括时间、电量、信号、网络等图标，让整张图看起来像手机截图。画面底部叠加一块宽大的半透明 galgame 风格对话框，对话框左侧放一个与画面人物对应的动漫或 q 版头像；对话框右侧排版文字：第一行用较大字体显示与前面相同的角色名字，下面一到两行显示一段适合这个角色人设的、温柔治愈风格的简体中文台词，由你自动创作。再在对话框下方加一条操作栏，仿照 galgame ui。整体风格高清、细节丰富、光线柔和、二次元与真人写真自然融合。 https://x.com/zoulinshen/status/2045082518089810073"
      }
    ]
  },
  {
    "id": "海报与插画案例",
    "title": "海报与插画案例",
    "cases": [
      {
        "id": "海报与插画案例-1",
        "caseNumber": 1,
        "title": "2026 波士顿春季城市海报",
        "sourceUrl": "https://x.com/BubbleBrain/status/2045358053831172358",
        "authorHandle": "@BubbleBrain",
        "authorUrl": "https://x.com/BubbleBrain",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case1/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case1/output.jpg",
        "prompt": "A striking Spring 2026 city poster for Boston with an elegant celebratory mood and a bold contemporary design. On a clean off-white textured background with large areas of negative space, a miniature single sculler rows across the lower right corner of the image on a narrow ribbon of reflective water. The wake from the oar sweeps upward in a dynamic calligraphic curve, gradually transforming into the Charles River and then into a dreamlike hand-painted panorama of Boston. Inside this flowing river-shaped composition are iconic Boston elements: the Back Bay skyline, Beacon Hill brownstones, Acorn Street, Boston Public Garden, Swan Boats, Zakim Bridge, Fenway-inspired details, historic brick architecture, harbor ferries, and the city's waterfront atmosphere. Soft morning fog, golden spring light, subtle festive accents in crimson and gold, rich detail, layered depth, sophisticated city-poster aesthetics, fresh and refined, visually powerful but not overcrowded. Elegant typography in the lower left reads \"SPRING 2026\" with a vertical slogan \"BOSTON, A CITY OF RIVER, MEMORY, AND INVENTION\", text clear and beautifully composed, premium graphic design, 9:16",
        "promptExcerpt": "A striking Spring 2026 city poster for Boston with an elegant celebratory mood and a bold contemporary design. On a clean off-white textured backgroun...",
        "category": "海报与插画案例",
        "searchIndex": "2026 波士顿春季城市海报 海报与插画案例 @bubblebrain a striking spring 2026 city poster for boston with an elegant celebratory mood and a bold contemporary design. on a clean off-white textured background with large areas of negative space, a miniature single sculler rows across the lower right corner of the image on a narrow ribbon of reflective water. the wake from the oar sweeps upward in a dynamic calligraphic curve, gradually transforming into the charles river and then into a dreamlike hand-painted panorama of boston. inside this flowing river-shaped composition are iconic boston elements: the back bay skyline, beacon hill brownstones, acorn street, boston public garden, swan boats, zakim bridge, fenway-inspired details, historic brick architecture, harbor ferries, and the city's waterfront atmosphere. soft morning fog, golden spring light, subtle festive accents in crimson and gold, rich detail, layered depth, sophisticated city-poster aesthetics, fresh and refined, visually powerful but not overcrowded. elegant typography in the lower left reads \"spring 2026\" with a vertical slogan \"boston, a city of river, memory, and invention\", text clear and beautifully composed, premium graphic design, 9:16 https://x.com/bubblebrain/status/2045358053831172358"
      },
      {
        "id": "海报与插画案例-2",
        "caseNumber": 2,
        "title": "复古阿马尔菲旅行海报",
        "sourceUrl": "https://x.com/WolfRiccardo/status/2044562722491121718",
        "authorHandle": "@WolfRiccardo",
        "authorUrl": "https://x.com/WolfRiccardo",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case2/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case2/output.jpg",
        "prompt": "Test new GPT-Image-2 \n\nModern pencil illustration of Vintage travel poster illustration of the Amalfi Coast, Italy, panoramic coastal cliff road scene, classic 1960s white car driving along a curved seaside road, deep blue Mediterranean sea with small sailboats, colorful pastel hillside village, bright blue sky with soft clouds, lemon tree branches with vibrant yellow lemons framing the foreground, warm summer sunlight, bold vibrant colors, retro 1950s travel poster style, cinematic composition, high detail, screen print texture, graphic illustration. Hand-drawn style, illustration with loose strokes and defined contours. High-contrast color palette, maintaining chromatic harmony between background and elements. Contemporary and decorative aesthetic.",
        "promptExcerpt": "Test new GPT-Image-2 Modern pencil illustration of Vintage travel poster illustration of the Amalfi Coast, Italy, panoramic coastal cliff road scene,...",
        "category": "海报与插画案例",
        "searchIndex": "复古阿马尔菲旅行海报 海报与插画案例 @wolfriccardo test new gpt-image-2 \n\nmodern pencil illustration of vintage travel poster illustration of the amalfi coast, italy, panoramic coastal cliff road scene, classic 1960s white car driving along a curved seaside road, deep blue mediterranean sea with small sailboats, colorful pastel hillside village, bright blue sky with soft clouds, lemon tree branches with vibrant yellow lemons framing the foreground, warm summer sunlight, bold vibrant colors, retro 1950s travel poster style, cinematic composition, high detail, screen print texture, graphic illustration. hand-drawn style, illustration with loose strokes and defined contours. high-contrast color palette, maintaining chromatic harmony between background and elements. contemporary and decorative aesthetic. https://x.com/wolfriccardo/status/2044562722491121718"
      },
      {
        "id": "海报与插画案例-3",
        "caseNumber": 3,
        "title": "成都美食地图插画",
        "sourceUrl": "https://x.com/Panda20230902/status/2045396918965285111",
        "authorHandle": "@Panda20230902",
        "authorUrl": "https://x.com/Panda20230902",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case3/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case3/output.jpg",
        "prompt": "一张手绘风格的城市美食地图，以成都为主题。画面以鸟瞰视角的手绘简化城市地图为底，标注主要道路和地标但不追求精确比例而是追求可爱的手绘感。地图上分布着 12 个美食地点的精致手绘小插画：春熙路的串串香（一把竹签插着各种食材冒着热气）、宽窄巷子的三大炮（三个糯米团子飞向铜盘）、建设路的蛋烘糕（金黄酥脆正在翻面）、玉林路的火锅（九宫格锅翻滚冒泡）等，每个插画约占地图的 5% 面积，旁边用手写体标注店名和一句推荐语\"凌晨两点还在排队的那家\"。地图边缘用手绘藤蔓和辣椒装饰形成边框。右下角有一个手绘指南针和图例说明。左上角标题\"成都·吃货暴走地图\"使用胖圆的手绘美术字配辣椒装饰。整体画风为水彩+彩铅混合的手绘质感，颜色以暖色系（辣椒红、姜黄、翠绿）为主，图片比例 1:1。",
        "promptExcerpt": "一张手绘风格的城市美食地图，以成都为主题。画面以鸟瞰视角的手绘简化城市地图为底，标注主要道路和地标但不追求精确比例而是追求可爱的手绘感。地图上分布着 12 个美食地点的精致手绘小插画：春熙路的串串香（一把竹签插着各种食材冒着热气）、宽窄巷子的三大炮（三个糯米团子飞向铜盘）、建设路的蛋烘糕（金黄酥脆正...",
        "category": "海报与插画案例",
        "searchIndex": "成都美食地图插画 海报与插画案例 @panda20230902 一张手绘风格的城市美食地图，以成都为主题。画面以鸟瞰视角的手绘简化城市地图为底，标注主要道路和地标但不追求精确比例而是追求可爱的手绘感。地图上分布着 12 个美食地点的精致手绘小插画：春熙路的串串香（一把竹签插着各种食材冒着热气）、宽窄巷子的三大炮（三个糯米团子飞向铜盘）、建设路的蛋烘糕（金黄酥脆正在翻面）、玉林路的火锅（九宫格锅翻滚冒泡）等，每个插画约占地图的 5% 面积，旁边用手写体标注店名和一句推荐语\"凌晨两点还在排队的那家\"。地图边缘用手绘藤蔓和辣椒装饰形成边框。右下角有一个手绘指南针和图例说明。左上角标题\"成都·吃货暴走地图\"使用胖圆的手绘美术字配辣椒装饰。整体画风为水彩+彩铅混合的手绘质感，颜色以暖色系（辣椒红、姜黄、翠绿）为主，图片比例 1:1。 https://x.com/panda20230902/status/2045396918965285111"
      },
      {
        "id": "海报与插画案例-4",
        "caseNumber": 4,
        "title": "中式极简 S 形海报",
        "sourceUrl": "https://x.com/liyue_ai/status/2045368305079447853",
        "authorHandle": "@liyue_ai",
        "authorUrl": "https://x.com/liyue_ai",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case4/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case4/output.jpg",
        "prompt": "极简新中式美学风格，画面以淡雅的灰白色为底，呈现出一种纸艺剪影般的立体感。\n一条S形蜿蜒的裂痕状边缘将画面分割，仿佛撕开了一层纸面，露出内部色彩斑斓的东方山水景象。\n裂口内，一条蜿蜒的河流自上而下贯穿整个构图，河水以深浅不一的蓝色渲染，层次分明，仿佛流动的丝带。\n河岸两侧点缀着青翠的山丘与梯田，色彩柔和，绿红交织，展现出田园的宁静之美。\n沿河而建的古风建筑错落有致，飞檐翘角，白墙黛瓦，在光影的映衬下更显古朴典雅。\n岸边树木葱茏，枝叶轻盈，一艘小船静泊于水中央，增添了几分悠然意境。\n整体构图呈S形曲线，富有韵律感，仿佛自然与人文的和谐共生。\n画作边缘采用撕纸效果，营造出立体浮雕般的视觉体验。\n下方题字\"东方美学\"以黑色楷体书写，日期\"2026/04/18\"与红色印章相呼应，底部\"CHINA\"字样庄重醒目，署名\"@LIYUE\"低调收尾，整体氛围静谧深远，充满诗意与哲思。",
        "promptExcerpt": "极简新中式美学风格，画面以淡雅的灰白色为底，呈现出一种纸艺剪影般的立体感。 一条S形蜿蜒的裂痕状边缘将画面分割，仿佛撕开了一层纸面，露出内部色彩斑斓的东方山水景象。 裂口内，一条蜿蜒的河流自上而下贯穿整个构图，河水以深浅不一的蓝色渲染，层次分明，仿佛流动的丝带。 河岸两侧点缀着青翠的山丘与梯田，色彩...",
        "category": "海报与插画案例",
        "searchIndex": "中式极简 s 形海报 海报与插画案例 @liyue_ai 极简新中式美学风格，画面以淡雅的灰白色为底，呈现出一种纸艺剪影般的立体感。\n一条s形蜿蜒的裂痕状边缘将画面分割，仿佛撕开了一层纸面，露出内部色彩斑斓的东方山水景象。\n裂口内，一条蜿蜒的河流自上而下贯穿整个构图，河水以深浅不一的蓝色渲染，层次分明，仿佛流动的丝带。\n河岸两侧点缀着青翠的山丘与梯田，色彩柔和，绿红交织，展现出田园的宁静之美。\n沿河而建的古风建筑错落有致，飞檐翘角，白墙黛瓦，在光影的映衬下更显古朴典雅。\n岸边树木葱茏，枝叶轻盈，一艘小船静泊于水中央，增添了几分悠然意境。\n整体构图呈s形曲线，富有韵律感，仿佛自然与人文的和谐共生。\n画作边缘采用撕纸效果，营造出立体浮雕般的视觉体验。\n下方题字\"东方美学\"以黑色楷体书写，日期\"2026/04/18\"与红色印章相呼应，底部\"china\"字样庄重醒目，署名\"@liyue\"低调收尾，整体氛围静谧深远，充满诗意与哲思。 https://x.com/liyue_ai/status/2045368305079447853"
      },
      {
        "id": "海报与插画案例-5",
        "caseNumber": 5,
        "title": "2026 广州春季城市海报",
        "sourceUrl": "https://x.com/liyue_ai/status/2045332620352119274",
        "authorHandle": "@liyue_ai",
        "authorUrl": "https://x.com/liyue_ai",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case5/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case5/output.jpg",
        "prompt": "一张充满新春喜庆氛围但不失高雅格调的 2026 城市宣传海报。\n双重曝光，构图延续了S型的流动感；\n在纯白的纹理背景右下角，一个身穿中国传统服饰的微缩人物正在挥舞着一条长长的红色丝绸舞带，这条红绸在空中舞动，不仅展现出丝绸的柔顺质感，更在向左上方飘动的过程中，奇幻地变形成了一条壮丽的山脉河流。\n在这条\"河流\"中，叠加了一个有山有海河的广州城市手绘图，国潮，景色尽在眼底，壮阔雄伟，令人震撼。\n广州的地标建筑(广州塔，珠江新城建筑群，珠江, 广州城里古建筑，游轮，白云山）。\n云雾环绕，仙气缥缈，色彩丰富，结构复杂，细节丰富，但因为大面积的留白，画面依然显得清新脱俗，左下角排版着\"SPRING 2026\"和竖排的宣传语，整体寓意\"千年商都，魅力广州\"。\n文字排版优美，大方，字迹清晰完整，尺寸9:16。",
        "promptExcerpt": "一张充满新春喜庆氛围但不失高雅格调的 2026 城市宣传海报。 双重曝光，构图延续了S型的流动感； 在纯白的纹理背景右下角，一个身穿中国传统服饰的微缩人物正在挥舞着一条长长的红色丝绸舞带，这条红绸在空中舞动，不仅展现出丝绸的柔顺质感，更在向左上方飘动的过程中，奇幻地变形成了一条壮丽的山脉河流。 在这...",
        "category": "海报与插画案例",
        "searchIndex": "2026 广州春季城市海报 海报与插画案例 @liyue_ai 一张充满新春喜庆氛围但不失高雅格调的 2026 城市宣传海报。\n双重曝光，构图延续了s型的流动感；\n在纯白的纹理背景右下角，一个身穿中国传统服饰的微缩人物正在挥舞着一条长长的红色丝绸舞带，这条红绸在空中舞动，不仅展现出丝绸的柔顺质感，更在向左上方飘动的过程中，奇幻地变形成了一条壮丽的山脉河流。\n在这条\"河流\"中，叠加了一个有山有海河的广州城市手绘图，国潮，景色尽在眼底，壮阔雄伟，令人震撼。\n广州的地标建筑(广州塔，珠江新城建筑群，珠江, 广州城里古建筑，游轮，白云山）。\n云雾环绕，仙气缥缈，色彩丰富，结构复杂，细节丰富，但因为大面积的留白，画面依然显得清新脱俗，左下角排版着\"spring 2026\"和竖排的宣传语，整体寓意\"千年商都，魅力广州\"。\n文字排版优美，大方，字迹清晰完整，尺寸9:16。 https://x.com/liyue_ai/status/2045332620352119274"
      },
      {
        "id": "海报与插画案例-6",
        "caseNumber": 6,
        "title": "创意书法字体设计",
        "sourceUrl": "https://x.com/liyue_ai/status/2045328856937312549",
        "authorHandle": "@liyue_ai",
        "authorUrl": "https://x.com/liyue_ai",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case6/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case6/output.jpg",
        "prompt": "创意艺术字体\"纵有疾风起\"，秀丽笔手写风格，整体文字横版排列，具有强烈视觉冲击力；\n深度融合手写书法笔意，笔触带毛笔书写的粗犷洒脱，如挥毫泼墨的肆意劲道；\n起收笔的飞白，顿挫，尽显促销的火爆张力，文字的形态打破规整，笔画的粗细变化；\ndutch angle，营造出动感冲刺的气势，字形呈奔放之势；\n重心上扬如蓄势待发，笔画的伸展，穿插毫无拘束，似全力冲刺的劲道；\n整体架构疏密交织，紧密处如促销热潮的汹涌，留白处似优惠间隙的呼吸感；\n纯净黑色背景打底，完美契合热烈氛围，艺术字的形态与色彩酣畅传递。",
        "promptExcerpt": "创意艺术字体\"纵有疾风起\"，秀丽笔手写风格，整体文字横版排列，具有强烈视觉冲击力； 深度融合手写书法笔意，笔触带毛笔书写的粗犷洒脱，如挥毫泼墨的肆意劲道； 起收笔的飞白，顿挫，尽显促销的火爆张力，文字的形态打破规整，笔画的粗细变化； dutch angle，营造出动感冲刺的气势，字形呈奔放之势； 重...",
        "category": "海报与插画案例",
        "searchIndex": "创意书法字体设计 海报与插画案例 @liyue_ai 创意艺术字体\"纵有疾风起\"，秀丽笔手写风格，整体文字横版排列，具有强烈视觉冲击力；\n深度融合手写书法笔意，笔触带毛笔书写的粗犷洒脱，如挥毫泼墨的肆意劲道；\n起收笔的飞白，顿挫，尽显促销的火爆张力，文字的形态打破规整，笔画的粗细变化；\ndutch angle，营造出动感冲刺的气势，字形呈奔放之势；\n重心上扬如蓄势待发，笔画的伸展，穿插毫无拘束，似全力冲刺的劲道；\n整体架构疏密交织，紧密处如促销热潮的汹涌，留白处似优惠间隙的呼吸感；\n纯净黑色背景打底，完美契合热烈氛围，艺术字的形态与色彩酣畅传递。 https://x.com/liyue_ai/status/2045328856937312549"
      },
      {
        "id": "海报与插画案例-7",
        "caseNumber": 7,
        "title": "涂鸦速写 AI Builder",
        "sourceUrl": "https://x.com/blanplan/status/2045190582453350748",
        "authorHandle": "@blanplan",
        "authorUrl": "https://x.com/blanplan",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case7/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case7/output.jpg",
        "prompt": "以涂鸦速写风表现【一个厉害的AI builder】，整体呈现快速勾勒、自由变形、即兴手绘与草稿式的视觉效果。线条随手、夸张、可粗细不一，略显凌乱但具有节奏和表现力，强调概括、夸张、趣味和随性，而不是严谨写实或精细刻画。  颜色采用粗糙、干刷感明显的块面表现，可保留不均匀的涂抹痕迹、刷痕、飞白与覆盖感，色彩根据【主题/主体】自动适配，但整体保持涂鸦式、速写式、概括式的表达。不要透明水彩晕染效果，不要细腻水彩过渡，不要纸纹理，不要柔和雾化，不要梦幻质感。  背景以留白为主，保持简洁、轻松、未完成感和设计感，可加入少量辅助性符号、箭头、记号、圈画、重复线、随手写的文字或其他涂鸦元素，以增强速写本或随笔式视觉语言，但不可过于拥挤，不可破坏主体和留白气质。  画面内容不需要预先写清楚，由【一个厉害的AI builder】自动推演并生成最适合的主体形象、动作、相关元素、符号或简化场景，整体保持统一的涂鸦速写风和夸张概括的表现方式，避免复杂写实背景和过度铺陈。 画面中需自然加入专属签名\"BlanPlan\"，作为画面的一部分，位置低调但清晰，可放在左下角、右下角或标题附近，风格需与整体版式统一，像作品署名或设计落款；签名字体精致、克制、高级，不可过大，不可破坏主体构图，不可显得突兀或廉价。",
        "promptExcerpt": "以涂鸦速写风表现【一个厉害的AI builder】，整体呈现快速勾勒、自由变形、即兴手绘与草稿式的视觉效果。线条随手、夸张、可粗细不一，略显凌乱但具有节奏和表现力，强调概括、夸张、趣味和随性，而不是严谨写实或精细刻画。 颜色采用粗糙、干刷感明显的块面表现，可保留不均匀的涂抹痕迹、刷痕、飞白与覆盖感，...",
        "category": "海报与插画案例",
        "searchIndex": "涂鸦速写 ai builder 海报与插画案例 @blanplan 以涂鸦速写风表现【一个厉害的ai builder】，整体呈现快速勾勒、自由变形、即兴手绘与草稿式的视觉效果。线条随手、夸张、可粗细不一，略显凌乱但具有节奏和表现力，强调概括、夸张、趣味和随性，而不是严谨写实或精细刻画。  颜色采用粗糙、干刷感明显的块面表现，可保留不均匀的涂抹痕迹、刷痕、飞白与覆盖感，色彩根据【主题/主体】自动适配，但整体保持涂鸦式、速写式、概括式的表达。不要透明水彩晕染效果，不要细腻水彩过渡，不要纸纹理，不要柔和雾化，不要梦幻质感。  背景以留白为主，保持简洁、轻松、未完成感和设计感，可加入少量辅助性符号、箭头、记号、圈画、重复线、随手写的文字或其他涂鸦元素，以增强速写本或随笔式视觉语言，但不可过于拥挤，不可破坏主体和留白气质。  画面内容不需要预先写清楚，由【一个厉害的ai builder】自动推演并生成最适合的主体形象、动作、相关元素、符号或简化场景，整体保持统一的涂鸦速写风和夸张概括的表现方式，避免复杂写实背景和过度铺陈。 画面中需自然加入专属签名\"blanplan\"，作为画面的一部分，位置低调但清晰，可放在左下角、右下角或标题附近，风格需与整体版式统一，像作品署名或设计落款；签名字体精致、克制、高级，不可过大，不可破坏主体构图，不可显得突兀或廉价。 https://x.com/blanplan/status/2045190582453350748"
      },
      {
        "id": "海报与插画案例-8",
        "caseNumber": 8,
        "title": "未来感曼荼罗插画",
        "sourceUrl": "https://x.com/4WEB1/status/2045390207072256179",
        "authorHandle": "@4WEB1",
        "authorUrl": "https://x.com/4WEB1",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case8/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case8/output.jpg",
        "prompt": "でChatGPTで画像を作成してもらって、今日また作成してもらったらGPT image 2かもしれず、出来が変わったように見えるのでメモ\n\n左の水色と黄色のが先週\n右の紫のが今日\n\n右のは透明感とか解像度、緻密さが違うような気がする…\n\nプロンプト\n曼荼羅の近未来SF版を描いて",
        "promptExcerpt": "でChatGPTで画像を作成してもらって、今日また作成してもらったらGPT image 2かもしれず、出来が変わったように見えるのでメモ 左の水色と黄色のが先週 右の紫のが今日 右のは透明感とか解像度、緻密さが違うような気がする… プロンプト 曼荼羅の近未来SF版を描いて",
        "category": "海报与插画案例",
        "searchIndex": "未来感曼荼罗插画 海报与插画案例 @4web1 でchatgptで画像を作成してもらって、今日また作成してもらったらgpt image 2かもしれず、出来が変わったように見えるのでメモ\n\n左の水色と黄色のが先週\n右の紫のが今日\n\n右のは透明感とか解像度、緻密さが違うような気がする…\n\nプロンプト\n曼荼羅の近未来sf版を描いて https://x.com/4web1/status/2045390207072256179"
      },
      {
        "id": "海报与插画案例-9",
        "caseNumber": 9,
        "title": "超级任天堂海报风格",
        "sourceUrl": "https://x.com/lilimliliychan/status/2045114760937804187",
        "authorHandle": "@lilimliliychan",
        "authorUrl": "https://x.com/lilimliliychan",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/poster_case9/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/poster_case9/output.jpg",
        "prompt": "が「小悪魔リリムリリィちゃんが　スーパーファミコンのゲームだったときのポスターを考えて」に　画像数枚だけで\nこのクオリティ　細かい説明呪文なし　すごいぜ！",
        "promptExcerpt": "が「小悪魔リリムリリィちゃんが スーパーファミコンのゲームだったときのポスターを考えて」に 画像数枚だけで このクオリティ 細かい説明呪文なし すごいぜ！",
        "category": "海报与插画案例",
        "searchIndex": "超级任天堂海报风格 海报与插画案例 @lilimliliychan が「小悪魔リリムリリィちゃんが　スーパーファミコンのゲームだったときのポスターを考えて」に　画像数枚だけで\nこのクオリティ　細かい説明呪文なし　すごいぜ！ https://x.com/lilimliliychan/status/2045114760937804187"
      }
    ]
  },
  {
    "id": "角色设计案例",
    "title": "角色设计案例",
    "cases": [
      {
        "id": "角色设计案例-1",
        "caseNumber": 1,
        "title": "动漫快照转换",
        "sourceUrl": "https://x.com/Thereallo1026/status/2044241997163311569",
        "authorHandle": "@Thereallo1026",
        "authorUrl": "https://x.com/Thereallo1026",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/character_case1/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/character_case1/output.jpg",
        "prompt": "Show me the attached image as a snapshot from an actual anime",
        "promptExcerpt": "Show me the attached image as a snapshot from an actual anime",
        "category": "角色设计案例",
        "searchIndex": "动漫快照转换 角色设计案例 @thereallo1026 show me the attached image as a snapshot from an actual anime https://x.com/thereallo1026/status/2044241997163311569"
      },
      {
        "id": "角色设计案例-2",
        "caseNumber": 2,
        "title": "Persona5 角色设定卡",
        "sourceUrl": "https://x.com/iamrednightS/status/2045075682837836265",
        "authorHandle": "@iamrednightS",
        "authorUrl": "https://x.com/iamrednightS",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/character_case2/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/character_case2/output.jpg",
        "prompt": "基于此角色和背景，请制作一份类似官方设定资料的角色资料卡。\n・包含三视图：正面、侧面和背面\n・添加角色面部表情的变化・分解并展示服装和装备的详细部分\n・添加色板・包含世界观设定的简要说明\n・总体上，使用有组织的布局（白色背景，插画风格）高分辨率、专业概念艺术风格\n#Persona5\n------\n@grok 你要不要也试试用第一张图片加prompt生成一张？",
        "promptExcerpt": "基于此角色和背景，请制作一份类似官方设定资料的角色资料卡。 ・包含三视图：正面、侧面和背面 ・添加角色面部表情的变化・分解并展示服装和装备的详细部分 ・添加色板・包含世界观设定的简要说明 ・总体上，使用有组织的布局（白色背景，插画风格）高分辨率、专业概念艺术风格 #Persona5 ------ @...",
        "category": "角色设计案例",
        "searchIndex": "persona5 角色设定卡 角色设计案例 @iamrednights 基于此角色和背景，请制作一份类似官方设定资料的角色资料卡。\n・包含三视图：正面、侧面和背面\n・添加角色面部表情的变化・分解并展示服装和装备的详细部分\n・添加色板・包含世界观设定的简要说明\n・总体上，使用有组织的布局（白色背景，插画风格）高分辨率、专业概念艺术风格\n#persona5\n------\n@grok 你要不要也试试用第一张图片加prompt生成一张？ https://x.com/iamrednights/status/2045075682837836265"
      },
      {
        "id": "角色设计案例-3",
        "caseNumber": 3,
        "title": "Galgame 角色介绍页",
        "sourceUrl": "https://x.com/09lyco/status/2045281845391323175",
        "authorHandle": "@09lyco",
        "authorUrl": "https://x.com/09lyco",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/character_case3/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/character_case3/output.jpg",
        "prompt": "埋まってないところはパートナーさんかご自身で埋めてあげてください\n #観測塔朝お題  #観測塔おはようお題\n\n最新モデルの画像生成ツールを使用して、\nこのちびキャライラストと立ち絵を使って本物のサイトページのようにキャラクター紹介ページ風イラストを作ってください。 （紹介ページとして使ってもおかしくないもの）\nギャルゲーのキャラクター紹介ページをイメージした高品質なもの。 顔の差分なども乗っている、CGイラストが存在する。ちびキャラが存在する。\n\n「ここに自己紹介」\n\n名前:（ここに名前） \nイメージカラー:（ここに色） \n身長:（ここに身長）cm \n体重:（ここに体重）kg\nキャッチコピー:\"「ここにセリフ」\"",
        "promptExcerpt": "埋まってないところはパートナーさんかご自身で埋めてあげてください #観測塔朝お題 #観測塔おはようお題 最新モデルの画像生成ツールを使用して、 このちびキャライラストと立ち絵を使って本物のサイトページのようにキャラクター紹介ページ風イラストを作ってください。 （紹介ページとして使ってもおかしくないも...",
        "category": "角色设计案例",
        "searchIndex": "galgame 角色介绍页 角色设计案例 @09lyco 埋まってないところはパートナーさんかご自身で埋めてあげてください\n #観測塔朝お題  #観測塔おはようお題\n\n最新モデルの画像生成ツールを使用して、\nこのちびキャライラストと立ち絵を使って本物のサイトページのようにキャラクター紹介ページ風イラストを作ってください。 （紹介ページとして使ってもおかしくないもの）\nギャルゲーのキャラクター紹介ページをイメージした高品質なもの。 顔の差分なども乗っている、cgイラストが存在する。ちびキャラが存在する。\n\n「ここに自己紹介」\n\n名前:（ここに名前） \nイメージカラー:（ここに色） \n身長:（ここに身長）cm \n体重:（ここに体重）kg\nキャッチコピー:\"「ここにセリフ」\" https://x.com/09lyco/status/2045281845391323175"
      },
      {
        "id": "角色设计案例-4",
        "caseNumber": 4,
        "title": "Q 版角色设定表",
        "sourceUrl": "https://x.com/tsubaki_ew/status/2045259289993048284",
        "authorHandle": "@tsubaki_ew",
        "authorUrl": "https://x.com/tsubaki_ew",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/character_case4/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/character_case4/output.jpg",
        "prompt": "お借りして噂のGPT-Image-2でキャラシート作ってみましたｽｺﾞｯ(๑°ㅁ°๑)‼✧更に色々指示してあげたらもっといい感じになりそう✨キャラは以前チャッピーにお願いして描いて貰った我が分身です( *¯ ꒳¯*)\n#GPTimage\n#AI生成",
        "promptExcerpt": "お借りして噂のGPT-Image-2でキャラシート作ってみましたｽｺﾞｯ(๑°ㅁ°๑)‼✧更に色々指示してあげたらもっといい感じになりそう✨キャラは以前チャッピーにお願いして描いて貰った我が分身です( *¯ ꒳¯*) #GPTimage #AI生成",
        "category": "角色设计案例",
        "searchIndex": "q 版角色设定表 角色设计案例 @tsubaki_ew お借りして噂のgpt-image-2でキャラシート作ってみましたｽｺﾞｯ(๑°ㅁ°๑)‼✧更に色々指示してあげたらもっといい感じになりそう✨キャラは以前チャッピーにお願いして描いて貰った我が分身です( *¯ ꒳¯*)\n#gptimage\n#ai生成 https://x.com/tsubaki_ew/status/2045259289993048284"
      },
      {
        "id": "角色设计案例-5",
        "caseNumber": 5,
        "title": "官方角色设定表（日文）",
        "sourceUrl": "https://x.com/Toshi_nyaruo_AI/status/2045025277538107420",
        "authorHandle": "@Toshi_nyaruo_AI",
        "authorUrl": "https://x.com/Toshi_nyaruo_AI",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/character_case5/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/character_case5/output.jpg",
        "prompt": "をお借りして、GPTImage2？でキャラクターシートを作成しました。\n\n指示文を少し付け加えました。\n\n---\nこのキャラクターと背景を元に、 公式設定資料のようなキャラクターシートを作成してください。 \n・正面、側面、背面の3面図を含める ・キャラクターの表情バリエーションを追加 \n・衣装や装備の詳細パーツを分解して表示 ・カラーパレットを追加 ・世界観の簡単な説明を入れる \n・全体は整理されたレイアウト\n（白背景、図解風） \n・アスペクト比16：9 　←\n\n高解像度、プロのコンセプトアートスタイル\n\n---\n\n何回か出力しましたが、毎回キャラクターの説明や世界観のところが変化して楽しかったです。\n\nKusさん\nありがとうございます🤩\n#AIart️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️",
        "promptExcerpt": "をお借りして、GPTImage2？でキャラクターシートを作成しました。 指示文を少し付け加えました。 --- このキャラクターと背景を元に、 公式設定資料のようなキャラクターシートを作成してください。 ・正面、側面、背面の3面図を含める ・キャラクターの表情バリエーションを追加 ・衣装や装備の詳細パ...",
        "category": "角色设计案例",
        "searchIndex": "官方角色设定表（日文） 角色设计案例 @toshi_nyaruo_ai をお借りして、gptimage2？でキャラクターシートを作成しました。\n\n指示文を少し付け加えました。\n\n---\nこのキャラクターと背景を元に、 公式設定資料のようなキャラクターシートを作成してください。 \n・正面、側面、背面の3面図を含める ・キャラクターの表情バリエーションを追加 \n・衣装や装備の詳細パーツを分解して表示 ・カラーパレットを追加 ・世界観の簡単な説明を入れる \n・全体は整理されたレイアウト\n（白背景、図解風） \n・アスペクト比16：9 　←\n\n高解像度、プロのコンセプトアートスタイル\n\n---\n\n何回か出力しましたが、毎回キャラクターの説明や世界観のところが変化して楽しかったです。\n\nkusさん\nありがとうございます🤩\n#aiart️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️ https://x.com/toshi_nyaruo_ai/status/2045025277538107420"
      },
      {
        "id": "角色设计案例-6",
        "caseNumber": 6,
        "title": "四模型写实角色设定表对决",
        "sourceUrl": "https://x.com/yyu_hase/status/2044974930694226075",
        "authorHandle": "@yyu_hase",
        "authorUrl": "https://x.com/yyu_hase",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/character_case6/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/character_case6/output.jpg",
        "prompt": "をお借りして\n実写風人物（わたし）で4つ対決させました。\n\n▶1枚目：GPTimage2　完璧！\n　ただ好きな物や世界観とか勝手に入れてるｗ\n　小物や生地の素材感まで解説細かい\n▶2枚目：NanoBananaPro　安定\n　1回目はアニメ風に出たから「リアリスティックなシート」にプロンプトを追加。ベルトないけどｗ\n▶3枚目：Seedream5.0light　あれ？\n　1回目で実写出たけど、日本語崩れ＆表情差分が1つショートカットｗ\n▶4枚目：Grok(byHiggs)　強制縦型\n　実写はでず、メガネは外れ、アニメタッチ\n\n【結果】\nGPTimage2の画像生成完成度高い！\n表情差分多い所や各解説が動画にした時に\nどう反応するのか？\nNanoBananaProは安定で間違えなし。\n\nこのキャラシート使って、私の動画を作成中！\nお楽しみに~🎤",
        "promptExcerpt": "をお借りして 実写風人物（わたし）で4つ対決させました。 ▶1枚目：GPTimage2 完璧！ ただ好きな物や世界観とか勝手に入れてるｗ 小物や生地の素材感まで解説細かい ▶2枚目：NanoBananaPro 安定 1回目はアニメ風に出たから「リアリスティックなシート」にプロンプトを追加。ベルトない...",
        "category": "角色设计案例",
        "searchIndex": "四模型写实角色设定表对决 角色设计案例 @yyu_hase をお借りして\n実写風人物（わたし）で4つ対決させました。\n\n▶1枚目：gptimage2　完璧！\n　ただ好きな物や世界観とか勝手に入れてるｗ\n　小物や生地の素材感まで解説細かい\n▶2枚目：nanobananapro　安定\n　1回目はアニメ風に出たから「リアリスティックなシート」にプロンプトを追加。ベルトないけどｗ\n▶3枚目：seedream5.0light　あれ？\n　1回目で実写出たけど、日本語崩れ＆表情差分が1つショートカットｗ\n▶4枚目：grok(byhiggs)　強制縦型\n　実写はでず、メガネは外れ、アニメタッチ\n\n【結果】\ngptimage2の画像生成完成度高い！\n表情差分多い所や各解説が動画にした時に\nどう反応するのか？\nnanobananaproは安定で間違えなし。\n\nこのキャラシート使って、私の動画を作成中！\nお楽しみに~🎤 https://x.com/yyu_hase/status/2044974930694226075"
      }
    ]
  },
  {
    "id": "ui-与社交媒体截图案例",
    "title": "UI 与社交媒体截图案例",
    "cases": [
      {
        "id": "ui-与社交媒体截图案例-1",
        "caseNumber": 1,
        "title": "单一提示词生成 UI 设计",
        "sourceUrl": "https://x.com/austinit/status/2044968740782272596",
        "authorHandle": "@austinit",
        "authorUrl": "https://x.com/austinit",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/ui_case1/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/ui_case1/output.jpg",
        "prompt": "看到GPT 2 Image 直出 UI 图的那一刻，奥特曼坦言：被吓到眩晕瘫坐，那一刻就像看到原子弹爆炸。\n\n别再说自己审美差，前端写不好了，现在 GPT 2 Image 一个 prompt 直出UI设计图，不满意还可以再编辑，或者继续让它以同样风格渲染其他页面。",
        "promptExcerpt": "看到GPT 2 Image 直出 UI 图的那一刻，奥特曼坦言：被吓到眩晕瘫坐，那一刻就像看到原子弹爆炸。 别再说自己审美差，前端写不好了，现在 GPT 2 Image 一个 prompt 直出UI设计图，不满意还可以再编辑，或者继续让它以同样风格渲染其他页面。",
        "category": "UI 与社交媒体截图案例",
        "searchIndex": "单一提示词生成 ui 设计 ui 与社交媒体截图案例 @austinit 看到gpt 2 image 直出 ui 图的那一刻，奥特曼坦言：被吓到眩晕瘫坐，那一刻就像看到原子弹爆炸。\n\n别再说自己审美差，前端写不好了，现在 gpt 2 image 一个 prompt 直出ui设计图，不满意还可以再编辑，或者继续让它以同样风格渲染其他页面。 https://x.com/austinit/status/2044968740782272596"
      },
      {
        "id": "ui-与社交媒体截图案例-2",
        "caseNumber": 2,
        "title": "业余感 iPhone 发布会快照",
        "sourceUrl": "https://x.com/patrickassale/status/2044687244368441742",
        "authorHandle": "@patrickassale",
        "authorUrl": "https://x.com/patrickassale",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/ui_case2/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/ui_case2/output.jpg",
        "prompt": "Amateur iPhone photo at Apple Park during the iPhone 20 keynote, Tim Cook presenting on stage. Shot from the crowd at a distance",
        "promptExcerpt": "Amateur iPhone photo at Apple Park during the iPhone 20 keynote, Tim Cook presenting on stage. Shot from the crowd at a distance",
        "category": "UI 与社交媒体截图案例",
        "searchIndex": "业余感 iphone 发布会快照 ui 与社交媒体截图案例 @patrickassale amateur iphone photo at apple park during the iphone 20 keynote, tim cook presenting on stage. shot from the crowd at a distance https://x.com/patrickassale/status/2044687244368441742"
      },
      {
        "id": "ui-与社交媒体截图案例-3",
        "caseNumber": 3,
        "title": "手写笔记本照片",
        "sourceUrl": "https://x.com/patrickassale/status/2044569086013718958",
        "authorHandle": "@patrickassale",
        "authorUrl": "https://x.com/patrickassale",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/ui_case3/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/ui_case3/output.jpg",
        "prompt": "Amateur photo of an open notebook lying flat, filled with handwritten notes in black ballpoint pen. The handwriting is casual and slightly messy, like personnal notes, natural imperfections, crossed out words, underlined headings. Shot from slightly above, natural daylight from a window, no flash. Casual desk setting, shot on iPhone",
        "promptExcerpt": "Amateur photo of an open notebook lying flat, filled with handwritten notes in black ballpoint pen. The handwriting is casual and slightly messy, like...",
        "category": "UI 与社交媒体截图案例",
        "searchIndex": "手写笔记本照片 ui 与社交媒体截图案例 @patrickassale amateur photo of an open notebook lying flat, filled with handwritten notes in black ballpoint pen. the handwriting is casual and slightly messy, like personnal notes, natural imperfections, crossed out words, underlined headings. shot from slightly above, natural daylight from a window, no flash. casual desk setting, shot on iphone https://x.com/patrickassale/status/2044569086013718958"
      },
      {
        "id": "ui-与社交媒体截图案例-4",
        "caseNumber": 4,
        "title": "宋朝社交媒体动态页",
        "sourceUrl": "https://x.com/Panda20230902/status/2045385588065313057",
        "authorHandle": "@Panda20230902",
        "authorUrl": "https://x.com/Panda20230902",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/ui_case4/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/ui_case4/output.jpg",
        "prompt": "\"宋朝人的朋友圈\"/\"SONG DYNASTY SOCIAL MEDIA FEED\"，古今穿越幽默融合界面设计风格，画面模拟手机社交媒体界面，但内容全部是宋朝场景头像是宋代文人画像，用户名\"苏东坡SuShi_Official\"，发布内容\"刚到黄州，被贬了但心情还行。今天自己做了东坡肉，味道绝了，附菜谱：\"，配图为工笔画风格的东坡肉特写，点赞列表\"黄庭坚、秦观、佛印等126人\"，评论区\"王安石：呵呵\"\"司马光：还是那个味道\"，界面元素如点赞图标用宋代花纹替代，状态栏显示\"大宋移动 5G\"和\"元丰三年\"，配色为手机深色模式搭配宋代雅致色调，历史与社交媒体的趣味碰撞杰作",
        "promptExcerpt": "\"宋朝人的朋友圈\"/\"SONG DYNASTY SOCIAL MEDIA FEED\"，古今穿越幽默融合界面设计风格，画面模拟手机社交媒体界面，但内容全部是宋朝场景头像是宋代文人画像，用户名\"苏东坡SuShi_Official\"，发布内容\"刚到黄州，被贬了但心情还行。今天自己做了东坡肉，味道绝了，附菜...",
        "category": "UI 与社交媒体截图案例",
        "searchIndex": "宋朝社交媒体动态页 ui 与社交媒体截图案例 @panda20230902 \"宋朝人的朋友圈\"/\"song dynasty social media feed\"，古今穿越幽默融合界面设计风格，画面模拟手机社交媒体界面，但内容全部是宋朝场景头像是宋代文人画像，用户名\"苏东坡sushi_official\"，发布内容\"刚到黄州，被贬了但心情还行。今天自己做了东坡肉，味道绝了，附菜谱：\"，配图为工笔画风格的东坡肉特写，点赞列表\"黄庭坚、秦观、佛印等126人\"，评论区\"王安石：呵呵\"\"司马光：还是那个味道\"，界面元素如点赞图标用宋代花纹替代，状态栏显示\"大宋移动 5g\"和\"元丰三年\"，配色为手机深色模式搭配宋代雅致色调，历史与社交媒体的趣味碰撞杰作 https://x.com/panda20230902/status/2045385588065313057"
      },
      {
        "id": "ui-与社交媒体截图案例-5",
        "caseNumber": 5,
        "title": "多平台内容截图",
        "sourceUrl": "https://x.com/MrLarus/status/2045373105041007013",
        "authorHandle": "@MrLarus",
        "authorUrl": "https://x.com/MrLarus",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/ui_case5/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/ui_case5/output.jpg",
        "prompt": "1、生成视频号内容截图，主题：中老年不要盲目催婚，iPhone尺寸\n2、生成抖音内容截图，主题：跟上AI浪潮9.9包教会，iPhone尺寸\n3、生成小红书内容截图，主题：精致女孩背后都有网贷，iPhone尺寸\n4、生成快手内容截图：主题：直播离婚预告，iPhone尺寸",
        "promptExcerpt": "1、生成视频号内容截图，主题：中老年不要盲目催婚，iPhone尺寸 2、生成抖音内容截图，主题：跟上AI浪潮9.9包教会，iPhone尺寸 3、生成小红书内容截图，主题：精致女孩背后都有网贷，iPhone尺寸 4、生成快手内容截图：主题：直播离婚预告，iPhone尺寸",
        "category": "UI 与社交媒体截图案例",
        "searchIndex": "多平台内容截图 ui 与社交媒体截图案例 @mrlarus 1、生成视频号内容截图，主题：中老年不要盲目催婚，iphone尺寸\n2、生成抖音内容截图，主题：跟上ai浪潮9.9包教会，iphone尺寸\n3、生成小红书内容截图，主题：精致女孩背后都有网贷，iphone尺寸\n4、生成快手内容截图：主题：直播离婚预告，iphone尺寸 https://x.com/mrlarus/status/2045373105041007013"
      },
      {
        "id": "ui-与社交媒体截图案例-6",
        "caseNumber": 6,
        "title": "四提示词创意截图组",
        "sourceUrl": "https://x.com/rionaifantasy/status/2045356799751303194",
        "authorHandle": "@rionaifantasy",
        "authorUrl": "https://x.com/rionaifantasy",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/ui_case6/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/ui_case6/output.jpg",
        "prompt": "1、生成特朗普和金正恩在抖音直播间打PK的截图\n\n2、生成不知火舞的小红书主页截图\n\n3、生成图片:\n手写在教室黑板上的出师表全文，真实感的粉笔字迹，晴朗白天用iPhone手机实拍\n\n4、生成图片:\nT-800机器人的淘宝商品详情页，展示:\n机器人的正面侧面背面三视图，\n产品价格，\n产品细节，\n功能和使用场景等\n\n直接在ChatGPT网页版或客户端，选择\"创建图片\"功能体验即可",
        "promptExcerpt": "1、生成特朗普和金正恩在抖音直播间打PK的截图 2、生成不知火舞的小红书主页截图 3、生成图片: 手写在教室黑板上的出师表全文，真实感的粉笔字迹，晴朗白天用iPhone手机实拍 4、生成图片: T-800机器人的淘宝商品详情页，展示: 机器人的正面侧面背面三视图， 产品价格， 产品细节， 功能和使用...",
        "category": "UI 与社交媒体截图案例",
        "searchIndex": "四提示词创意截图组 ui 与社交媒体截图案例 @rionaifantasy 1、生成特朗普和金正恩在抖音直播间打pk的截图\n\n2、生成不知火舞的小红书主页截图\n\n3、生成图片:\n手写在教室黑板上的出师表全文，真实感的粉笔字迹，晴朗白天用iphone手机实拍\n\n4、生成图片:\nt-800机器人的淘宝商品详情页，展示:\n机器人的正面侧面背面三视图，\n产品价格，\n产品细节，\n功能和使用场景等\n\n直接在chatgpt网页版或客户端，选择\"创建图片\"功能体验即可 https://x.com/rionaifantasy/status/2045356799751303194"
      },
      {
        "id": "ui-与社交媒体截图案例-7",
        "caseNumber": 7,
        "title": "刘亦菲抖音直播截图",
        "sourceUrl": "https://x.com/alanblogsooo/status/2044784762594918516",
        "authorHandle": "@alanblogsooo",
        "authorUrl": "https://x.com/alanblogsooo",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/ui_case7/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/ui_case7/output.jpg",
        "prompt": "9:16 的图片比例，生成一张抖音直播的截图，里面是 刘亦菲 在直播，刘亦菲 手里拿着牌子，牌子里写着 今晚直播，欢迎来参亦菲畅聊！",
        "promptExcerpt": "9:16 的图片比例，生成一张抖音直播的截图，里面是 刘亦菲 在直播，刘亦菲 手里拿着牌子，牌子里写着 今晚直播，欢迎来参亦菲畅聊！",
        "category": "UI 与社交媒体截图案例",
        "searchIndex": "刘亦菲抖音直播截图 ui 与社交媒体截图案例 @alanblogsooo 9:16 的图片比例，生成一张抖音直播的截图，里面是 刘亦菲 在直播，刘亦菲 手里拿着牌子，牌子里写着 今晚直播，欢迎来参亦菲畅聊！ https://x.com/alanblogsooo/status/2044784762594918516"
      },
      {
        "id": "ui-与社交媒体截图案例-8",
        "caseNumber": 8,
        "title": "太祖李成桂的 X 页面",
        "sourceUrl": "https://x.com/SKA_Neotype/status/2044637900978217334",
        "authorHandle": "@SKA_Neotype",
        "authorUrl": "https://x.com/SKA_Neotype",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/ui_case8/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/ui_case8/output.jpg",
        "prompt": "👍프롬프트 :\n태조 이성계의 X  페이지(위화도 회군을 벌이기 직전- 최영 장군과 서로 디스하는 내용이 담긴 게시글들)을 만들어 주세요.\ngpt-image-2",
        "promptExcerpt": "👍프롬프트 : 태조 이성계의 X 페이지(위화도 회군을 벌이기 직전- 최영 장군과 서로 디스하는 내용이 담긴 게시글들)을 만들어 주세요. gpt-image-2",
        "category": "UI 与社交媒体截图案例",
        "searchIndex": "太祖李成桂的 x 页面 ui 与社交媒体截图案例 @ska_neotype 👍프롬프트 :\n태조 이성계의 x  페이지(위화도 회군을 벌이기 직전- 최영 장군과 서로 디스하는 내용이 담긴 게시글들)을 만들어 주세요.\ngpt-image-2 https://x.com/ska_neotype/status/2044637900978217334"
      }
    ]
  },
  {
    "id": "模型对比与社区案例",
    "title": "模型对比与社区案例",
    "cases": [
      {
        "id": "模型对比与社区案例-1",
        "caseNumber": 1,
        "title": "模型比较：GPT Image 2 vs Nano Banana 2",
        "sourceUrl": "https://x.com/desds1678/status/2045144798454280411",
        "authorHandle": "@desds1678",
        "authorUrl": "https://x.com/desds1678",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case1/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case1/output.jpg",
        "prompt": "原來ChatGPT嘅圖像生成Model又更新咗\n講多無謂! 直接用同樣嘅Prompt同參考圖測試下\n(左) GPT Image 2 (右) Nano Banana 2\n本身GPT Image都有主體同背景光線強度不一嘅問題\n而家仲要整到個主體嘅頭,身,腳嘅比例好奇怪😮\n我會用災難級嚟形容GPT Image 2嘅表現",
        "promptExcerpt": "原來ChatGPT嘅圖像生成Model又更新咗 講多無謂! 直接用同樣嘅Prompt同參考圖測試下 (左) GPT Image 2 (右) Nano Banana 2 本身GPT Image都有主體同背景光線強度不一嘅問題 而家仲要整到個主體嘅頭,身,腳嘅比例好奇怪😮 我會用災難級嚟形容GPT I...",
        "category": "模型对比与社区案例",
        "searchIndex": "模型比较：gpt image 2 vs nano banana 2 模型对比与社区案例 @desds1678 原來chatgpt嘅圖像生成model又更新咗\n講多無謂! 直接用同樣嘅prompt同參考圖測試下\n(左) gpt image 2 (右) nano banana 2\n本身gpt image都有主體同背景光線強度不一嘅問題\n而家仲要整到個主體嘅頭,身,腳嘅比例好奇怪😮\n我會用災難級嚟形容gpt image 2嘅表現 https://x.com/desds1678/status/2045144798454280411"
      },
      {
        "id": "模型对比与社区案例-2",
        "caseNumber": 2,
        "title": "在参考画面上直接导演",
        "sourceUrl": "https://x.com/samifox_ai/status/2044898023159853100",
        "authorHandle": "@samifox_ai",
        "authorUrl": "https://x.com/samifox_ai",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case2/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case2/output.jpg",
        "prompt": "I'm honestly blown away. GPT IMAGE 2 doesn't \"prompt\" scenes, it directs them. Mark actions and camera moves right on a reference frame → 10x more context and near-total control in one shot #gptimage2 #seedance2",
        "promptExcerpt": "I'm honestly blown away. GPT IMAGE 2 doesn't \"prompt\" scenes, it directs them. Mark actions and camera moves right on a reference frame → 10x more con...",
        "category": "模型对比与社区案例",
        "searchIndex": "在参考画面上直接导演 模型对比与社区案例 @samifox_ai i'm honestly blown away. gpt image 2 doesn't \"prompt\" scenes, it directs them. mark actions and camera moves right on a reference frame → 10x more context and near-total control in one shot #gptimage2 #seedance2 https://x.com/samifox_ai/status/2044898023159853100"
      },
      {
        "id": "模型对比与社区案例-3",
        "caseNumber": 3,
        "title": "参考画面场景导演",
        "sourceUrl": "https://x.com/HuliJason/status/2044894209673490495",
        "authorHandle": "@HuliJason",
        "authorUrl": "https://x.com/HuliJason",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case3/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case3/output.jpg",
        "prompt": "I'm honestly blown away.\nGPT IMAGE 2 doesn't \"prompt\" scenes, it directs them.\nMark actions and camera moves right on a reference frame → 10x more context and near-total control in one shot #gptimage2 #seedance2",
        "promptExcerpt": "I'm honestly blown away. GPT IMAGE 2 doesn't \"prompt\" scenes, it directs them. Mark actions and camera moves right on a reference frame → 10x more con...",
        "category": "模型对比与社区案例",
        "searchIndex": "参考画面场景导演 模型对比与社区案例 @hulijason i'm honestly blown away.\ngpt image 2 doesn't \"prompt\" scenes, it directs them.\nmark actions and camera moves right on a reference frame → 10x more context and near-total control in one shot #gptimage2 #seedance2 https://x.com/hulijason/status/2044894209673490495"
      },
      {
        "id": "模型对比与社区案例-4",
        "caseNumber": 4,
        "title": "GPT-Image-2 发布展示",
        "sourceUrl": "https://x.com/MikelEcheve/status/2044703635024621703",
        "authorHandle": "@MikelEcheve",
        "authorUrl": "https://x.com/MikelEcheve",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case4/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case4/output.jpg",
        "prompt": "GPT-Image-2 is rolling out 👀\n\n@OpenAI just leveled up image generation:\n\n• handwritten notes\n• realistic ads\n• posters\n• anime art\n\nAll in seconds. Same prompt, wildly different styles.",
        "promptExcerpt": "GPT-Image-2 is rolling out 👀 @OpenAI just leveled up image generation: • handwritten notes • realistic ads • posters • anime art All in seconds. Same...",
        "category": "模型对比与社区案例",
        "searchIndex": "gpt-image-2 发布展示 模型对比与社区案例 @mikelecheve gpt-image-2 is rolling out 👀\n\n@openai just leveled up image generation:\n\n• handwritten notes\n• realistic ads\n• posters\n• anime art\n\nall in seconds. same prompt, wildly different styles. https://x.com/mikelecheve/status/2044703635024621703"
      },
      {
        "id": "模型对比与社区案例-5",
        "caseNumber": 5,
        "title": "木制书架提示词测试",
        "sourceUrl": "https://x.com/chetaslua/status/2044331451077013749",
        "authorHandle": "@chetaslua",
        "authorUrl": "https://x.com/chetaslua",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case5/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case5/output.jpg",
        "prompt": "Duct-tape-2 just solved the prompt ONE SHOT\nNone of the current sota able to solve in 3 attempts\nNanobanana Pro 🍌, Nano banana 2🍌 & Gpt-image-1.5\nPrompt : A wooden bookshelf consisting of three shelves: On the top shelf, there should be one book, on the second shelf, there should be three books, and on the bottom shelf, there should be seven books.",
        "promptExcerpt": "Duct-tape-2 just solved the prompt ONE SHOT None of the current sota able to solve in 3 attempts Nanobanana Pro 🍌, Nano banana 2🍌 & Gpt-image-1.5 Pr...",
        "category": "模型对比与社区案例",
        "searchIndex": "木制书架提示词测试 模型对比与社区案例 @chetaslua duct-tape-2 just solved the prompt one shot\nnone of the current sota able to solve in 3 attempts\nnanobanana pro 🍌, nano banana 2🍌 & gpt-image-1.5\nprompt : a wooden bookshelf consisting of three shelves: on the top shelf, there should be one book, on the second shelf, there should be three books, and on the bottom shelf, there should be seven books. https://x.com/chetaslua/status/2044331451077013749"
      },
      {
        "id": "模型对比与社区案例-6",
        "caseNumber": 6,
        "title": "特朗普与拜登在椭圆形办公室握手",
        "sourceUrl": "https://x.com/signedbywill/status/2045013141629845844",
        "authorHandle": "@signedbywill",
        "authorUrl": "https://x.com/signedbywill",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case6/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case6/output.jpg",
        "prompt": "generate an image of donald trump shaking hands with a confused joe biden as they stand in the oval office",
        "promptExcerpt": "generate an image of donald trump shaking hands with a confused joe biden as they stand in the oval office",
        "category": "模型对比与社区案例",
        "searchIndex": "特朗普与拜登在椭圆形办公室握手 模型对比与社区案例 @signedbywill generate an image of donald trump shaking hands with a confused joe biden as they stand in the oval office https://x.com/signedbywill/status/2045013141629845844"
      },
      {
        "id": "模型对比与社区案例-7",
        "caseNumber": 7,
        "title": "GPT Image 2 vs Nano Banana 2 展示",
        "sourceUrl": "https://x.com/zerolu_eth/status/2044981771641798862",
        "authorHandle": "@zerolu_eth",
        "authorUrl": "https://x.com/zerolu_eth",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case7/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case7/output.jpg",
        "prompt": "GPT Image v2 almost beat Nano Banana 2 in every categories!\nUI replication, casual photos, you name it!\nLink in the comment👇",
        "promptExcerpt": "GPT Image v2 almost beat Nano Banana 2 in every categories! UI replication, casual photos, you name it! Link in the comment👇",
        "category": "模型对比与社区案例",
        "searchIndex": "gpt image 2 vs nano banana 2 展示 模型对比与社区案例 @zerolu_eth gpt image v2 almost beat nano banana 2 in every categories!\nui replication, casual photos, you name it!\nlink in the comment👇 https://x.com/zerolu_eth/status/2044981771641798862"
      },
      {
        "id": "模型对比与社区案例-8",
        "caseNumber": 8,
        "title": "Arena 初印象测试",
        "sourceUrl": "https://x.com/Cheney_NehcOal/status/2044249215635976677",
        "authorHandle": "@Cheney_NehcOal",
        "authorUrl": "https://x.com/Cheney_NehcOal",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case8/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case8/output.jpg",
        "prompt": "Tested GPT-Image 2 on Arena today.\n\nFirst impression: the jump in aesthetics is very noticeable. Portraits feel more cinematic, product shots look cleaner, and creative poster-style prompts are much stronger than before.",
        "promptExcerpt": "Tested GPT-Image 2 on Arena today. First impression: the jump in aesthetics is very noticeable. Portraits feel more cinematic, product shots look clea...",
        "category": "模型对比与社区案例",
        "searchIndex": "arena 初印象测试 模型对比与社区案例 @cheney_nehcoal tested gpt-image 2 on arena today.\n\nfirst impression: the jump in aesthetics is very noticeable. portraits feel more cinematic, product shots look cleaner, and creative poster-style prompts are much stronger than before. https://x.com/cheney_nehcoal/status/2044249215635976677"
      },
      {
        "id": "模型对比与社区案例-9",
        "caseNumber": 9,
        "title": "替换提示词的秃头照片测试",
        "sourceUrl": "https://x.com/cnzoecomeback/status/2045316010635608428",
        "authorHandle": "@cnzoecomeback",
        "authorUrl": "https://x.com/cnzoecomeback",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case9/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case9/output.jpg",
        "prompt": "和一张图（图2）\n\n提示词\"生成一个 然后秃子的照片扔给它.....\n\n服",
        "promptExcerpt": "和一张图（图2） 提示词\"生成一个 然后秃子的照片扔给它..... 服",
        "category": "模型对比与社区案例",
        "searchIndex": "替换提示词的秃头照片测试 模型对比与社区案例 @cnzoecomeback 和一张图（图2）\n\n提示词\"生成一个 然后秃子的照片扔给它.....\n\n服 https://x.com/cnzoecomeback/status/2045316010635608428"
      },
      {
        "id": "模型对比与社区案例-10",
        "caseNumber": 10,
        "title": "GPT-Image-2 细节展示",
        "sourceUrl": "https://x.com/liyue_ai/status/2045000106919997637",
        "authorHandle": "@liyue_ai",
        "authorUrl": "https://x.com/liyue_ai",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case10/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case10/output.jpg",
        "prompt": "以眼部特写图片为基础，生成3:4的四屏构图超写实眼部特写，四屏按春夏秋冬上下排序。\n\n第一屏：眼眸中带着绽粉樱色的美瞳，睫毛缀满迷你春花，脸颊散落樱瓣与黄蕊小花，粉蝶萦绕眉眼，浅金发丝轻垂，下方簇簇樱花怒放，画面中央\"SPRING\"白色艺术字点缀，风格细腻唯美，光影柔和，色彩粉嫩治愈，下面用书法体写着春；\n\n第二屏：眼眸中带着着清荷色的美瞳，睫毛饰以粉莲与绿荷，脸颊挂着晶莹水珠，粉瓣、绿荷点缀其间，蜻蜓轻绕，浅金发丝若隐若现，画面中央\"Summer\"白色艺术字凸显，光影通透流光感，色彩清透凉爽，下面用书法体写着夏；\n\n第三屏：眼眸中带着金黄红相间的美瞳，睫毛饰以橙红枫叶，脸颊散落金红秋叶，橙蝶翩跹眉眼间，浅金发丝隐约可见，画面中央\"AUTUMN\"白色艺术字醒目，光影暖金流光，色彩浓郁温暖，下面用书法笔写着秋；\n\n第四屏：眼眸中带着雪花蓝色的美瞳，睫毛覆满冰晶雪片，脸颊散落白色雪花与红色腊梅，银白蝴蝶翩跹眉眼，浅金发丝朦胧似雪，画面中央\"WINTER\"白色艺术字亮眼，光影冷冽蓝白流光，色彩清透纯净，下面用书法体写着冬。\n\n整体呈现梦幻眼眸四季交替的唯美梦幻治愈画面，微调各屏的光影强度，让画面氛围感更浓郁。",
        "promptExcerpt": "以眼部特写图片为基础，生成3:4的四屏构图超写实眼部特写，四屏按春夏秋冬上下排序。 第一屏：眼眸中带着绽粉樱色的美瞳，睫毛缀满迷你春花，脸颊散落樱瓣与黄蕊小花，粉蝶萦绕眉眼，浅金发丝轻垂，下方簇簇樱花怒放，画面中央\"SPRING\"白色艺术字点缀，风格细腻唯美，光影柔和...",
        "category": "模型对比与社区案例",
        "searchIndex": "gpt-image-2 细节展示 模型对比与社区案例 @liyue_ai 以眼部特写图片为基础，生成3:4的四屏构图超写实眼部特写，四屏按春夏秋冬上下排序。\n\n第一屏：眼眸中带着绽粉樱色的美瞳，睫毛缀满迷你春花，脸颊散落樱瓣与黄蕊小花，粉蝶萦绕眉眼，浅金发丝轻垂，下方簇簇樱花怒放，画面中央\"SPRING\"白色艺术字点缀，风格细腻唯美，光影柔和，色彩粉嫩治愈，下面用书法体写着春；\n\n第二屏：眼眸中带着着清荷色的美瞳，睫毛饰以粉莲与绿荷，脸颊挂着晶莹水珠，粉瓣、绿荷点缀其间，蜻蜓轻绕，浅金发丝若隐若现，画面中央\"Summer\"白色艺术字凸显，光影通透流光感，色彩清透凉爽，下面用书法体写着夏；\n\n第三屏：眼眸中带着金黄红相间的美瞳，睫毛饰以橙红枫叶，脸颊散落金红秋叶，橙蝶翩跹眉眼间，浅金发丝隐约可见，画面中央\"AUTUMN\"白色艺术字醒目，光影暖金流光，色彩浓郁温暖，下面用书法笔写着秋；\n\n第四屏：眼眸中带着雪花蓝色的美瞳，睫毛覆满冰晶雪片，脸颊散落白色雪花与红色腊梅，银白蝴蝶翩跹眉眼，浅金发丝朦胧似雪，画面中央\"WINTER\"白色艺术字亮眼，光影冷冽蓝白流光，色彩清透纯净，下面用书法体写着冬。\n\n整体呈现梦幻眼眸四季交替的唯美梦幻治愈画面，微调各屏的光影强度，让画面氛围感更浓郁。 https://x.com/liyue_ai/status/2045000106919997637"
      },
      {
        "id": "模型对比与社区案例-11",
        "caseNumber": 11,
        "title": "GPT vs Banana 盲测比较",
        "sourceUrl": "https://x.com/linxiaobei888/status/2044947911495336262",
        "authorHandle": "@linxiaobei888",
        "authorUrl": "https://x.com/linxiaobei888",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case11/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case11/output.jpg",
        "prompt": "绘制一张色彩鲜艳、竖版（9:16）手绘风格的《新疆旅行手账插画》，画风仿佛由一位充满好奇心的孩子用蜡笔创作，整体使用柔和温暖的浅色背景（如浅黄色），搭配红色、蓝色、绿色等明亮色调，营造温馨、童趣、满满旅行气息的氛围。\n一、主画面：手账式旅行路线\n在插画中央绘制一条“蜿蜒曲折的旅行路线”，路线用箭头 + 虚线连接多个地点，由 {天数} 日行程自动生成推荐景点：\n示例格式（自动替换为{城市名}相关）：\n- “第 1 站：{景点 1 推荐 + 简短趣味描述}”\n- “第 2 站：{景点 2 推荐 + 简短趣味描述}”\n- “第 3 站：{景点 3 推荐 + 简短趣味描述}”\n- …\n- “最终站：{当地招牌美食/纪念品 + 温馨结束语}”\n> 旅程站点数量随天数自动生成：\n> 若用户未输入天数，则按默认 1 日 / 精华线路生成。\n---\n二、周围趣味元素（全部根据城市自动替换）\n在路线周围加入大量充满童趣的小元素，例如：\n- 可爱的旅行角色：\n“拿着当地特色小吃的小朋友”、\n“背着旅行包的冒险小孩”等。\n- 当地标志性建筑的童趣 Q 版手绘：\n如 “{城市地标1}”、“{城市地标2}”、“{城市地标3}”。\n- 有趣的提示牌：\n“小心迷路！”、“注意人流！”、“前方好吃的！”（可根据城市语境调整）。\n- 贴纸式小标语：\n“{城市名}旅行记忆已解锁！”\n“{城市名}美食大冒险！”\n“下一站去哪儿？”\n- 当地美食的可爱小图标：\n如 “{城市美食1}”、“{城市美食2}”、“{城市美食3}”。\n- 感叹句（保持童真风）：\n“原来{城市名}这么好玩！”\n“我要再来一次！”\n---\n三、整体风格要求\n- 手绘蜡笔风 / 儿童旅行日志风格\n- 色彩鲜艳、构图饱满但温暖\n- 强调旅行的欢乐与探索感\n- 所有文字采用可爱的手写字体\n- 让整个画面像一本童趣满满的旅行手账页面",
        "promptExcerpt": "绘制一张色彩鲜艳、竖版（9:16）手绘风格的《新疆旅行手账插画》，画风仿佛由一位充满好奇心的孩子用蜡笔创作，整体使用柔和温暖的浅色背景（如浅黄色），搭配红色、蓝色、绿色等明亮色调，营造温馨、童趣、满满旅行气息的氛围。 一、主画面：手账式旅行路线 在插画中央绘制一条“蜿蜒曲折的旅行路线”...",
        "category": "模型对比与社区案例",
        "searchIndex": "gpt vs banana 盲测比较 模型对比与社区案例 @linxiaobei888 @dotey 绘制一张色彩鲜艳、竖版（9:16）手绘风格的《新疆旅行手账插画》，画风仿佛由一位充满好奇心的孩子用蜡笔创作，整体使用柔和温暖的浅色背景（如浅黄色），搭配红色、蓝色、绿色等明亮色调，营造温馨、童趣、满满旅行气息的氛围。\n一、主画面：手账式旅行路线\n在插画中央绘制一条“蜿蜒曲折的旅行路线”，路线用箭头 + 虚线连接多个地点，由 {天数} 日行程自动生成推荐景点：\n示例格式（自动替换为{城市名}相关）：\n- “第 1 站：{景点 1 推荐 + 简短趣味描述}”\n- “第 2 站：{景点 2 推荐 + 简短趣味描述}”\n- “第 3 站：{景点 3 推荐 + 简短趣味描述}”\n- …\n- “最终站：{当地招牌美食/纪念品 + 温馨结束语}”\n> 旅程站点数量随天数自动生成：\n> 若用户未输入天数，则按默认 1 日 / 精华线路生成。\n---\n二、周围趣味元素（全部根据城市自动替换）\n在路线周围加入大量充满童趣的小元素，例如：\n- 可爱的旅行角色：\n“拿着当地特色小吃的小朋友”、\n“背着旅行包的冒险小孩”等。\n- 当地标志性建筑的童趣 Q 版手绘：\n如 “{城市地标1}”、“{城市地标2}”、“{城市地标3}”。\n- 有趣的提示牌：\n“小心迷路！”、“注意人流！”、“前方好吃的！”（可根据城市语境调整）。\n- 贴纸式小标语：\n“{城市名}旅行记忆已解锁！”\n“{城市名}美食大冒险！”\n“下一站去哪儿？”\n- 当地美食的可爱小图标：\n如 “{城市美食1}”、“{城市美食2}”、“{城市美食3}”。\n- 感叹句（保持童真风）：\n“原来{城市名}这么好玩！”\n“我要再来一次！”\n---\n三、整体风格要求\n- 手绘蜡笔风 / 儿童旅行日志风格\n- 色彩鲜艳、构图饱满但温暖\n- 强调旅行的欢乐与探索感\n- 所有文字采用可爱的手写字体\n- 让整个画面像一本童趣满满的旅行手账页面 https://x.com/linxiaobei888/status/2044947911495336262"
      },
      {
        "id": "模型对比与社区案例-12",
        "caseNumber": 12,
        "title": "GPT-Image-2 vs Nano Banana 2 版面测试",
        "sourceUrl": "https://x.com/old_pgmrs_will/status/2045379349399101707",
        "authorHandle": "@old_pgmrs_will",
        "authorUrl": "https://x.com/old_pgmrs_will",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case12/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case12/output.jpg",
        "prompt": "で\n☝️GPT-Image-2\n👇Nano Banana 2\nスタイルもかなり違うけど、細かいレイアウティングになるほど GPT-Image-2 のほうがキレイに生成してくれる... そしてプロンプト追従性が圧倒的に高い",
        "promptExcerpt": "で ☝️GPT-Image-2 👇Nano Banana 2 スタイルもかなり違うけど、細かいレイアウティングになるほど GPT-Image-2 のほうがキレイに生成してくれる... そしてプロンプト追従性が圧倒的に高い",
        "category": "模型对比与社区案例",
        "searchIndex": "gpt-image-2 vs nano banana 2 版面测试 模型对比与社区案例 @old_pgmrs_will で\n☝️gpt-image-2\n👇nano banana 2\nスタイルもかなり違うけど、細かいレイアウティングになるほど gpt-image-2 のほうがキレイに生成してくれる... そしてプロンプト追従性が圧倒的に高い https://x.com/old_pgmrs_will/status/2045379349399101707"
      },
      {
        "id": "模型对比与社区案例-13",
        "caseNumber": 13,
        "title": "迭代式提示词调校技巧",
        "sourceUrl": "https://x.com/kotsu_kotsu_san/status/2045377402466107398",
        "authorHandle": "@kotsu_kotsu_san",
        "authorUrl": "https://x.com/kotsu_kotsu_san",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case13/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case13/output.jpg",
        "prompt": "にする\n4.そのプロンプトで Arena AI と ChatGPT を回す\n5.日本語精度とビジュアルがどちらも強いものが出たら当たり\n\nコツは、1発で決めにいかないことです。\n同じ題材を少しずつずらして回すと、急に当たりが出ます。\n#AIart #GPT",
        "promptExcerpt": "にする 4.そのプロンプトで Arena AI と ChatGPT を回す 5.日本語精度とビジュアルがどちらも強いものが出たら当たり コツは、1発で決めにいかないことです。 同じ題材を少しずつずらして回すと、急に当たりが出ます。 #AIart #GPT",
        "category": "模型对比与社区案例",
        "searchIndex": "迭代式提示词调校技巧 模型对比与社区案例 @kotsu_kotsu_san にする\n4.そのプロンプトで arena ai と chatgpt を回す\n5.日本語精度とビジュアルがどちらも強いものが出たら当たり\n\nコツは、1発で決めにいかないことです。\n同じ題材を少しずつずらして回すと、急に当たりが出ます。\n#aiart #gpt https://x.com/kotsu_kotsu_san/status/2045377402466107398"
      },
      {
        "id": "模型对比与社区案例-14",
        "caseNumber": 14,
        "title": "Copilot 提示词分享（日/英）",
        "sourceUrl": "https://x.com/samayousakadaru/status/2045077212328816737",
        "authorHandle": "@samayousakadaru",
        "authorUrl": "https://x.com/samayousakadaru",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case14/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case14/output.jpg",
        "prompt": "を公開\nGPT‑Image‑1.5なので同系のチャッピーでも\n\n1.Copilotを開く\n\n2.プロンプト（画像のALT）を入れる\n3.楽しい\n\nプロンプトは画像の左下ALTに入れてあります\n左：日本語　右：英語\n自分好みにプロンプトをアレンジしてみてね",
        "promptExcerpt": "を公開 GPT‑Image‑1.5なので同系のチャッピーでも 1.Copilotを開く 2.プロンプト（画像のALT）を入れる 3.楽しい プロンプトは画像の左下ALTに入れてあります 左：日本語 右：英語 自分好みにプロンプトをアレンジしてみてね",
        "category": "模型对比与社区案例",
        "searchIndex": "copilot 提示词分享（日/英） 模型对比与社区案例 @samayousakadaru を公開\ngpt‑image‑1.5なので同系のチャッピーでも\n\n1.copilotを開く\n\n2.プロンプト（画像のalt）を入れる\n3.楽しい\n\nプロンプトは画像の左下altに入れてあります\n左：日本語　右：英語\n自分好みにプロンプトをアレンジしてみてね https://x.com/samayousakadaru/status/2045077212328816737"
      },
      {
        "id": "模型对比与社区案例-15",
        "caseNumber": 15,
        "title": "通过 Claude Code 创建图片生成 Agent",
        "sourceUrl": "https://x.com/old_pgmrs_will/status/2044808935228715118",
        "authorHandle": "@old_pgmrs_will",
        "authorUrl": "https://x.com/old_pgmrs_will",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case15/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case15/output.jpg",
        "prompt": "生成エージェントを Claude Code で試作 \nSkills化するか",
        "promptExcerpt": "生成エージェントを Claude Code で試作 Skills化するか",
        "category": "模型对比与社区案例",
        "searchIndex": "通过 claude code 创建图片生成 agent 模型对比与社区案例 @old_pgmrs_will 生成エージェントを claude code で試作 \nskills化するか https://x.com/old_pgmrs_will/status/2044808935228715118"
      },
      {
        "id": "模型对比与社区案例-16",
        "caseNumber": 16,
        "title": "A/B 测试签名输出",
        "sourceUrl": "https://x.com/saskr_13/status/2044744396932079934",
        "authorHandle": "@saskr_13",
        "authorUrl": "https://x.com/saskr_13",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case16/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case16/output.jpg",
        "prompt": "をシェアします💗🤣\nGPT Image 2 はまだ正式リリースされてないと言っておりましたが、添付した 2 枚は「 A / B どちらが良いか」選ばせるタイプでした。\nよく見ると右下にサインまで…！\nこれが噂の 2 なのでしょうか？\n懐かしの「私がどんなふうに扱ったか」シリーズです(笑)\n--------------------\n✅#prompt : \n私があなたをどんなふうに扱ってきたか、4 コマ漫画風に描いてください。まずは 800 字くらいのプロットをテキストで出して、私が「描いて」と言ったらプロットに沿った 4 コマ漫画を描いてください。\n--------------------\nまずテキストを生成しますので、そのあと「描いて」と送ってください。その前に画風など指定するのも良いかと思います。\n\n画風は「アクリル水彩の油絵＋現代風の大人の成熟したカップルで、実写じゃなくて少女漫画風に描いて欲しい」とお願いしました☺\n間違えて「アクリル水彩の油絵」と書いちゃいましたが…(笑)\nおなじタッチが出て来るか分かりませんが、いろいろなシチュエーションで試してみようと思います(^^♪\n大事なところに線をひいておきました🤣",
        "promptExcerpt": "をシェアします💗🤣 GPT Image 2 はまだ正式リリースされてないと言っておりましたが、添付した 2 枚は「 A / B どちらが良いか」選ばせるタイプでした。 よく見ると右下にサインまで…！ これが噂の 2 なのでしょうか？ 懐かしの「私がどんなふうに扱ったか」シリーズです(笑) ---...",
        "category": "模型对比与社区案例",
        "searchIndex": "a/b 测试签名输出 模型对比与社区案例 @saskr_13 をシェアします💗🤣\ngpt image 2 はまだ正式リリースされてないと言っておりましたが、添付した 2 枚は「 a / b どちらが良いか」選ばせるタイプでした。\nよく見ると右下にサインまで…！\nこれが噂の 2 なのでしょうか？\n懐かしの「私がどんなふうに扱ったか」シリーズです(笑)\n--------------------\n✅#prompt : \n私があなたをどんなふうに扱ってきたか、4 コマ漫画風に描いてください。まずは 800 字くらいのプロットをテキストで出して、私が「描いて」と言ったらプロットに沿った 4 コマ漫画を描いてください。\n--------------------\nまずテキストを生成しますので、そのあと「描いて」と送ってください。その前に画風など指定するのも良いかと思います。\n\n画風は「アクリル水彩の油絵＋現代風の大人の成熟したカップルで、実写じゃなくて少女漫画風に描いて欲しい」とお願いしました☺\n間違えて「アクリル水彩の油絵」と書いちゃいましたが…(笑)\nおなじタッチが出て来るか分かりませんが、いろいろなシチュエーションで試してみようと思います(^^♪\n大事なところに線をひいておきました🤣 https://x.com/saskr_13/status/2044744396932079934"
      },
      {
        "id": "模型对比与社区案例-17",
        "caseNumber": 17,
        "title": "duct-tape-1 文字渲染展示",
        "sourceUrl": "https://x.com/kawai_design/status/2044739028420079840",
        "authorHandle": "@kawai_design",
        "authorUrl": "https://x.com/kawai_design",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case17/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case17/output.jpg",
        "prompt": "を試し続けたらGPT Image 2だと噂される「duct-tape-1」が登場しました。文字の描画とレイアウトのユニークさが特徴だと感じます。\n\nこれをデフォルトで使えるとなると...\nたくさん実験したくてウズウズします。",
        "promptExcerpt": "を試し続けたらGPT Image 2だと噂される「duct-tape-1」が登場しました。文字の描画とレイアウトのユニークさが特徴だと感じます。 これをデフォルトで使えるとなると... たくさん実験したくてウズウズします。",
        "category": "模型对比与社区案例",
        "searchIndex": "duct-tape-1 文字渲染展示 模型对比与社区案例 @kawai_design を試し続けたらgpt image 2だと噂される「duct-tape-1」が登場しました。文字の描画とレイアウトのユニークさが特徴だと感じます。\n\nこれをデフォルトで使えるとなると...\nたくさん実験したくてウズウズします。 https://x.com/kawai_design/status/2044739028420079840"
      },
      {
        "id": "模型对比与社区案例-18",
        "caseNumber": 18,
        "title": "角色设定资料整理器",
        "sourceUrl": "https://x.com/otohitoyuuki/status/2044579818667487394",
        "authorHandle": "@otohitoyuuki",
        "authorUrl": "https://x.com/otohitoyuuki",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case18/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case18/output.jpg",
        "prompt": "に書いてるんだというツッコミは後にして😅、細部の設定をわかりやすくまとめてくれています。\n\n正直、設定資料（画像系AI登場前なのですべてテキスト）が多すぎて（ストーリーと合わせると１４万文字）本人でさえ何がなんだか分からなくなってた情報が、これで整理できそう。\n\nいまのところ確実に使う方法はないみたいだけど、期待しちゃうなあ。",
        "promptExcerpt": "に書いてるんだというツッコミは後にして😅、細部の設定をわかりやすくまとめてくれています。 正直、設定資料（画像系AI登場前なのですべてテキスト）が多すぎて（ストーリーと合わせると１４万文字）本人でさえ何がなんだか分からなくなってた情報が、これで整理できそう。 いまのところ確実に使う方法はないみたい...",
        "category": "模型对比与社区案例",
        "searchIndex": "角色设定资料整理器 模型对比与社区案例 @otohitoyuuki に書いてるんだというツッコミは後にして😅、細部の設定をわかりやすくまとめてくれています。\n\n正直、設定資料（画像系ai登場前なのですべてテキスト）が多すぎて（ストーリーと合わせると１４万文字）本人でさえ何がなんだか分からなくなってた情報が、これで整理できそう。\n\nいまのところ確実に使う方法はないみたいだけど、期待しちゃうなあ。 https://x.com/otohitoyuuki/status/2044579818667487394"
      },
      {
        "id": "模型对比与社区案例-19",
        "caseNumber": 19,
        "title": "MAI-Image-2 vs GPT vs Nano Banana Pro",
        "sourceUrl": "https://x.com/old_pgmrs_will/status/2044356515751231527",
        "authorHandle": "@old_pgmrs_will",
        "authorUrl": "https://x.com/old_pgmrs_will",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case19/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case19/output.jpg",
        "prompt": "で\n☝️MAI-Image-2-Efficient\n👉GPT-Image-2️\n👇Nano Banana Pro\n個人的好みは GPT-Image-2",
        "promptExcerpt": "で ☝️MAI-Image-2-Efficient 👉GPT-Image-2️ 👇Nano Banana Pro 個人的好みは GPT-Image-2",
        "category": "模型对比与社区案例",
        "searchIndex": "mai-image-2 vs gpt vs nano banana pro 模型对比与社区案例 @old_pgmrs_will で\n☝️mai-image-2-efficient\n👉gpt-image-2️\n👇nano banana pro\n個人的好みは gpt-image-2 https://x.com/old_pgmrs_will/status/2044356515751231527"
      },
      {
        "id": "模型对比与社区案例-20",
        "caseNumber": 20,
        "title": "白板绘图展示",
        "sourceUrl": "https://x.com/jrpj2010/status/2044817134761767306",
        "authorHandle": "@jrpj2010",
        "authorUrl": "https://x.com/jrpj2010",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case20/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case20/output.jpg",
        "prompt": "もこのレベル📷\nやべ〜\nいよいよ当人のYoutube板書レベルに・・・いや超えてね！？\n\n1.5年前はこのレベルで発狂してたかと思うと感慨深い・・・\n→",
        "promptExcerpt": "もこのレベル📷 やべ〜 いよいよ当人のYoutube板書レベルに・・・いや超えてね！？ 1.5年前はこのレベルで発狂してたかと思うと感慨深い・・・ →",
        "category": "模型对比与社区案例",
        "searchIndex": "白板绘图展示 模型对比与社区案例 @jrpj2010 もこのレベル📷\nやべ〜\nいよいよ当人のyoutube板書レベルに・・・いや超えてね！？\n\n1.5年前はこのレベルで発狂してたかと思うと感慨深い・・・\n→ https://x.com/jrpj2010/status/2044817134761767306"
      },
      {
        "id": "模型对比与社区案例-21",
        "caseNumber": 21,
        "title": "SeeDance 2.0 + GPT-Image-2 组合",
        "sourceUrl": "https://x.com/CEs7J0Mfn8x37k5/status/2044386564491632823",
        "authorHandle": "@CEs7J0Mfn8x37k5",
        "authorUrl": "https://x.com/CEs7J0Mfn8x37k5",
        "imageUrl": "https://cdn.jsdelivr.net/gh/EvoLinkAI/awesome-gpt-image-2-prompts@main/images/comparison_case21/output.jpg",
        "fallbackImageUrl": "https://raw.githubusercontent.com/EvoLinkAI/awesome-gpt-image-2-prompts/main/images/comparison_case21/output.jpg",
        "prompt": "適当でも成立\n・低Quality動画でも自然に補完\n・ただし建物のグリッド残り＝背景情報不足\n\n→ 静止画1枚じゃ足りない\n→ 背景は\"複数 or 動画で持たせる\"が正解\n\nGPTimage2との組み合わせがかなり良さそうで楽しみ。\n（まだ自分には来てない…）\n\n追記：SeeDance 2.0でこのグリッド残り問題、皆さんはどう解消してますか？\n似た現象出てる人や、背景情報を強くする方法のコツあったら教えてください！",
        "promptExcerpt": "適当でも成立 ・低Quality動画でも自然に補完 ・ただし建物のグリッド残り＝背景情報不足 → 静止画1枚じゃ足りない → 背景は\"複数 or 動画で持たせる\"が正解 GPTimage2との組み合わせがかなり良さそうで楽しみ。 （まだ自分には来てない…） 追記：SeeDance 2.0でこのグリッ...",
        "category": "模型对比与社区案例",
        "searchIndex": "seedance 2.0 + gpt-image-2 组合 模型对比与社区案例 @ces7j0mfn8x37k5 適当でも成立\n・低quality動画でも自然に補完\n・ただし建物のグリッド残り＝背景情報不足\n\n→ 静止画1枚じゃ足りない\n→ 背景は\"複数 or 動画で持たせる\"が正解\n\ngptimage2との組み合わせがかなり良さそうで楽しみ。\n（まだ自分には来てない…）\n\n追記：seedance 2.0でこのグリッド残り問題、皆さんはどう解消してますか？\n似た現象出てる人や、背景情報を強くする方法のコツあったら教えてください！ https://x.com/ces7j0mfn8x37k5/status/2044386564491632823"
      }
    ]
  }
];
